### ISSUE TITLE
Should the magnet focus be focusHighlightLayerable?

### ISSUE THREAD

**Issue by zepumph** [phetsims/faradays-law#110]
Notice how the focus is above the coils, but the magnet is below:

![image](https://user-images.githubusercontent.com/6856943/41480656-902adda0-707b-11e8-8ddc-7653737a307b.png)

Do we want to implement this with `focusHighlightLayerable`? That is what we did with the magnet view in friction so it tucks under the white background.

This is really a design question, so assigning to @terracoda, and also @mbarlow12 (lead dev); @jessegreenberg may be interested too.

**Comment by mbarlow12** [comment]
@zepumph We originally implemented as layerable, and I made an error in removing that part. I have it fixed in the latest version of the `jump` branch.

**Comment by terracoda** [comment]
@mbarlow12, the layering looks fine on master. I'm not sure how the magnet is suppose to work, but the layering is fine. I am unassigning myself.

![screen shot 2018-06-22 at 1 05 20 pm](https://user-images.githubusercontent.com/1902116/41785368-f49ac3d0-761c-11e8-8884-f90d15deab6d.png)

**Comment by mbarlow12** [comment]
Thanks @terracoda. Same for me, closing.
