### ISSUE TITLE
VoltageProperty should be in model, not in the Voltmeter

### ISSUE THREAD

**Issue by zepumph** [phetsims/faradays-law#112]
This line in the screenView looks buggy:

`    var bulbNode = new BulbNode( model.voltmeter.voltageProperty, {`

Instead we should have the VoltageProperty be a top level model Property. This will be more idiomatic for phet-io studio as well (since most other Properties are directly in the model).

**Comment by zepumph** [comment]
I made this change. @mbarlow12 please review. I hope this doesn't interfere with your "jump" branch too much. 

Also tagging @jbphet because this will likely break the sonifcation wrapper on next dev release.

**Comment by mbarlow12** [comment]
@zepumph the above changes look great, and I fuzzed for quite a while without error. Assigning back to you to close.

**Comment by zepumph** [comment]
Great thank you. Closing
