### ISSUE TITLE
Considerations for description iterations

### ISSUE THREAD

**Issue by terracoda** [phetsims/faradays-law#114]
@jhung and @mbarlow12, I just had a listen to Faraday's Law, and here are some considerations. It was too much to post in an issue, so maybe you two can create issues for anything you would like to actually take on.

Here's a link to the google doc, Considerations for Faraday's Law - August 15
https://docs.google.com/document/d/1Ja-cNL4yIAzJPb4qzHRE3HilIW36dP2200ZyEFBVxPo/edit#

**Comment by terracoda** [comment]
I can only assign @mbarlow12. I don't know how to assign @jhung.

**Comment by terracoda** [comment]
Of course, it will good to user's feedback before you consider my feedback to deeply :-)

**Comment by mbarlow12** [comment]
@terracoda Thanks for the feedback—I think some of your suggestions are pretty easy to implement, and I started that last night.

One bit of clarification. Will there be any difference in the AT output or navigation for the following two examples?

```html
<h2>Play Area</h2>
<section>
  <h3>Lightbulb circuit</h3>
  <p>info</p>
  <p>info</p>
  <h3>Magnet</h3>
  <ul>
    <li>listed info</li>
  </ul>
</section>
```
```html
<h2>Play Area</h2>
<h3>Lightbulb Circuit</h3>
<p>info</p>
<p>info</p>
<h3>Magnet</h3>
<ul>
  <li>listed info</li>
</ul>
```

I believe we're trying to move toward a flatter PDOM structure with fewer nested elements, and that's what I was hoping to achieve in the above commit. But let me know if this could negatively affect the user experience.

**Comment by terracoda** [comment]
@mbarlow12, if you want to create a landmark region called Play Area, the H2 should be inside the section element. A better comparison is:

``` html
<section>
<h2>Play Area</h2>
  <h3>Lightbulb circuit</h3>
  <p>info</p>
  <p>info</p>
  <h3>Magnet</h3>
  <ul>
    <li>listed info</li>
  </ul>
</section>

<h2>Play Area</h2>
<h3>Lightbulb Circuit</h3>
<p>info</p>
<p>info</p>
<h3>Magnet</h3>
<ul>
  <li>listed info</li>
</ul>
```

While they both have the same hierarchy, using a `section` element creates an additional navigable region. Users can navigate by region or by heading, though navigating by heading seems a little more common in the users I have seen. I am not sure if that is because regions are newer to HTML than headings.

**Comment by terracoda** [comment]
Just out of curiosity what is it about the magnet you want to put in a list structure? Something like this maybe?

Magnet
- in coil
- poles north-south

**Comment by mbarlow12** [comment]
The empty list is a bit of an error that's now fixed on master (it's also filled in once the polarity is flipped). I was improperly linking properties on sim start; it now looks like:

Magnet Polarity:
- north pole on left
- south pole on right

'right' and 'left' update as the polarity is flipped.

**Comment by terracoda** [comment]
@mbarlow12, if the is only one property shown at a time, I'd just use a p element, like so:

```html
<h3>Magnet Polarity</h3>
<p>north pole on left</p>
```

But I am confused. When is this content read out? Or what is it associated with or closest to? The interactive draggable Magnet, or the Flip Magnet button?

I'll check master ;-)

**Comment by jhung** [comment]
I recommend closing this to avoid any confusion with the new revised design.

**Comment by mbarlow12** [comment]
Can do!
