### ISSUE TITLE
Convert SimpleDragHandler ---> DragListener

### ISSUE THREAD

**Issue by zepumph** [phetsims/faradays-law#117]
"because it is the way of the future"

This should be done for FL trackable release.

**Comment by zepumph** [comment]
after phetsims/scenery#842, this will involve taking the "dragListener" piece out of the tandem.

**Comment by zepumph** [comment]
Discussion of whether or not to drop the "dragListener" tandem in https://github.com/phetsims/scenery/issues/854, for now I did drop it.

**Comment by zepumph** [comment]
Converted above. @samreid please review.

**Comment by zepumph** [comment]
es6 changes were implemented above. At first I committed a blanket conversion from self to this, but then had to go back for listeners passed to other types (like DragListener).

As for the DragListener implementation conversion, @samreid and I tried to get it working using a number of option combinations, but couldn't figure it out. We used `translateNode` with `mapLocation`, but found that the bounds were offset by the starting point of the magnet. I then played around more with `locationProperty`, `offsetLocation`, and `transform` (in different combinations), but only made things worse. @jonathanolson could you review the current implementation in `MagnetNodeWithField`. We are manually calculating and adjusting for the offset, which @samreid seemed to think was more work than we needed to do, but it is complicated by `FaradaysLawModel.moveMagnetToPosition` which validates the coil and sim bounds before setting the locationProperty. 

Do you think it could work to use `moveMagnetToPosition` as the `mapLocation` function that just returns the correct point?

That was a bit lengthy, and potentially convoluted. Please let me know if you would like to discuss further. 

Over to you @jonathanolson.

**Comment by samreid** [comment]
@zepumph I noticed that master still has the bar magnet sometimes jump when a drag starts--something may be wrong with the drag listener.

**Comment by zepumph** [comment]
Can you be more specific. I cannot reproduce. Furthermore this issue wasn't responsible for changing any of the logic in the `DragListener`

**Comment by zepumph** [comment]
I spoke with @samreid while addressing the bug fixed in the above commit. The offset was being calculated based on the center of the `MagnetNodeWithField`, but the model's magnet's `positionProperty` was being updated based on the translation of the Node. Thus there was a bit of a jump (depending on where you were in the screen) with the offset in between the `start` listener and the first `drag` call.

**Comment by samreid** [comment]
The blocking part of this issue was to use DragListener, so I'm going to unmark this for high-priority phet-io.  Though I'm realizing a good step before publication will be to go through all the open issues and address them as much as possible anyways.

**Comment by jbphet** [comment]
@zepumph - I'm going through issues in this repo in preparation for a re-release, and as far as I can `DragListener` is being used and the behavior looks fine.  I'm not sure why all assignees were removed.  Can you take a look and either close or describe what else needs to be addressed?

**Comment by zepumph** [comment]
As far as I can tell, this is ready for closing. I read through this issue, and compared the implementation in the above commits to master. If there are any bugs that seem related to dragging, please create a new issue.
