### ISSUE TITLE
Coordinate a11y and PhET-iO work for a PhET-iO release

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-law#118]
For #107 @zepumph @chrisklus and I are working on preparing a PhET-iO release.  We have a number of issues before that will be ready though.  But when it's time, we'll need to coordinate with @mbarlow12 and @jessegreenberg about making sure a11y development is in a consistent state and won't interfere with the release.  I think I'll leave this unassigned until @zepumph @chrisklus and I get closer to the PhET-iO RC.

**Comment by zepumph** [comment]
Faradays law is not a priority right now, this issue is very out of date. We will need to review all of FL again before publishing for PhET-iO again.
