### ISSUE TITLE
Add bar magnet keyboard control text to PDOM and accessible as help text

### ISSUE THREAD

**Issue by jhung** [phetsims/faradays-law#121]
Add keyboard control text to the bar magnet description that reads:
"Use the W A S D keys to move the magnet in four directions. Use 1 2 3 keys to slide magnet left and right."

This text should appear in the PDOM under the Bar Magnet description, and should be accessible as help text when the magnet is focused or hovered (similar to how help text is done for the books in Friction).

**Comment by mbarlow12** [comment]
@jhung, this should be done and can be accessed at:

https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.53/phet/faradays-law_a11y_view.html
or
https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.53/phet/faradays-law_en_phet.html?accessibility

**Comment by jhung** [comment]
Verified. Thanks!
