### ISSUE TITLE
Adjustments to coil description text

### ISSUE THREAD

**Issue by jhung** [phetsims/faradays-law#122]
Change the existing coil description from:
"The coil is open on the left and right - the bar magnet to pass through." (1 coil)
"The coils are open on the left and right - the bar magnet to pass through." (2 coils)

To:
"The coil is open on the left and right, large enough for the bar magnet to pass through." (1 coil)
"The coils are open on the left and right, large enough for the bar magnet to pass through." (2 coils)

**Comment by mbarlow12** [comment]
@jhung, this should be done and can be accessed at:

https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.53/phet/faradays-law_a11y_view.html
or
https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.53/phet/faradays-law_en_phet.html?accessibility

**Comment by jhung** [comment]
Upon reviewing, some minor changes.

Currently: 
"The coil is open on the left and right, large enough for the bar magnet can pass through." (1 coil)
"The coils are open on the left and right, large enough for the bar magnet to pass through." (2 coils)

Change to:
"The coil is sideways, with openings on the left and right." (1 coil)
"The two coils are sideways, with openings on the left and right." (2 coils)

**Comment by emily-phet** [comment]
Description design was paused, and will be revisited holistically at a later date. When that's done, we'll pull all issues related to past description efforts, and review.
