### ISSUE TITLE
When sliding starts, fire a shorter alert

### ISSUE THREAD

**Issue by jhung** [phetsims/faradays-law#123]
Currently, when a slide action starts, an alert like the following is fired: "Magnet sliding slowly to the right. Press Space to stop slide."

Change this alert to just state slide has started and space to stop: "Sliding [slide direction]. Space to stop."

The speed will be conveyed through the audio cues from sonification.

**Comment by mbarlow12** [comment]
@jhung this (and the other issue you opened) were finished a little while ago. I'm assigning back to you to close at your convenience.

**Comment by jhung** [comment]
Thanks for making the changes. I'm finding that even with the shorter alerts, it's likely the alert will continue to be read after the sliding has stopped. We might have to shorten this even further.

Also there's an issue with multiple slide alerts piling up if slide moves are done very quickly.

I will bring this up with discussions with @emily-phet and @terracoda when we meet.

**Comment by jhung** [comment]
No longer applicable with revised designs. Closing this issue.
