### ISSUE TITLE
Should "Field lines" be "Field Lines"?

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-law#124]
During #107 we noticed that it reads "Field lines".  Check other sims for precedent, we mostly saw Uppercase Uppercase, like

![image](https://user-images.githubusercontent.com/679486/45118092-a4f85300-b114-11e8-8015-815b6bf7513d.png)

or

![image](https://user-images.githubusercontent.com/679486/45118106-ade92480-b114-11e8-9ebf-b49dc46c9ec1.png)

![image](https://user-images.githubusercontent.com/679486/45118120-ba6d7d00-b114-11e8-9f17-857765107039.png)

**Comment by arouinfar** [comment]
@samreid in working on https://github.com/phetsims/sun/issues/370, I noticed that most sims use Title Case for checkbox strings. I found just one other instance of Sentence case in Trig Tour.

![image](https://user-images.githubusercontent.com/8419308/45118216-23ed8b80-b115-11e8-8562-5c056f664ed2.png)

**Comment by samreid** [comment]
@chrisklus @zepumph and I changed "Field lines" to "Field Lines" in https://github.com/phetsims/faradays-law/commit/b79ff18a1e25977c751f60f5f25b0e843ee82fd7 .  @ariel-phet is that an OK change for this circumstance?  I'll create a more general issue about whether we should visit more sims regarding casing.

**Comment by samreid** [comment]
Changed, closing.
