### ISSUE TITLE
Tweaks to labels and add help text for sim options

### ISSUE THREAD

**Issue by jhung** [phetsims/faradays-law#125]
Tweak various sim control labels to be more concise, and add help text for controls that currently lack it.

**Label: "Volt meter"**
Help Text: "Play with or without voltmeter connected to light bulb circuit"
Alerts:
* When unchecked: "Volt meter removed from circuit."
* When checked: "Volt meter connected to circuit."

**Label: "Field Lines"**
Help Text: "Add magnetic field lines."
Alerts:
* When unchecked: "Magnetic field lines hidden."
* When checked: "Magnetic field lines visible. Field Lines description updated."

**Label: "Circuit mode"**
Option 1 (default): "1 coil"
Option 2: "2 coils"
Help text: "Explore what happens with one or two different coils."
Alerts:
* Change from one to two coils: "Circuit now has two different coils."
* Change from two to one coil: "Circuit now has one coil."

**Label "Flip Magnet"**
Help text: "Flip North and South poles"
Alerts:
* If field lines not showing: "Magnet flipped. North pole  on ['left' / 'right']. South pole on ['right' / 'left']."
* If field lines showing: "North pole  on ['left' / 'right']. South pole on ['right' / 'left']. Field Line description updated."

**Comment by mbarlow12** [comment]
@jhung did we ever confirm if the strings should be `Volt meter` or `Voltmeter`?

**Comment by jhung** [comment]
@mbarlow12 
It looks like "voltmeter" is the proper term. https://en.wikipedia.org/wiki/Voltmeter

**Comment by jhung** [comment]
The inputs for the different sim options should use `aria-describedby` to associate the input with the descriptive paragraph that follows.

Applies to: Voltmeter and Field lines checkboxes.

Example:
```
<input tabindex="0" id="4-60-128-178" type="checkbox" value="" style="width: 1px; height: 1px;" aria-describedby="description-4-60-128-178">
<label tabindex="-1" id="label-4-60-128-178" for="4-60-128-178">Voltmeter</label>
<p tabindex="-1" id="description-4-60-128-178">Play with or without voltmeter connected to light bulb circuit</p>
```

**Comment by emily-phet** [comment]
This sim's description will be re-designed at a future date. When that's done, we'll review all past issues related to description.
