### ISSUE TITLE
Remove "show" from tandem from sim

### ISSUE THREAD

**Issue by zepumph** [phetsims/faradays-law#126]
There are two places where this is used and will need to be changed:

- [ ] for the two checkboxes, remove the `show` prefix, as `voltmeterCheckbox` and `fieldLinesCheckbox` is clear enough
- [ ] for model Properties, change the use of `show` to `visible`, i.e. `showFieldLinesProperty` -> `fieldLinesVisibleProperty`.

Assigning to many, for whoever gets to it first.

**Comment by samreid** [comment]
Proposed fix pushed above, @zepumph or @chrisklus please review.

**Comment by zepumph** [comment]
looks great. Thanks @samreid.
