### ISSUE TITLE
refactor a11y PDOM Node structure to separate node in MagnetNodeWithField

### ISSUE THREAD

**Issue by zepumph** [phetsims/faradays-law#127]
I see about 100 lines of code below `TODO: refactor into separate node(s)?` that to me seems like an easy refactor into a "MagnetInPDOMNode" or something like that. Since last december, MargnetNodeWIthField has almost doubled in size, and I think this would be a great step in simplifying the type again.

@mbarlow12 I'll let you go for it since you have been the lead in this file.

Note: please don't work on it this afternoon, as I am committing in the file for review of https://github.com/phetsims/faradays-law/issues/117.

**Comment by zepumph** [comment]
- [ ] Included in this work, from @samreid review: Can this be documented? `Number( event.key ) <= 3`

**Comment by mbarlow12** [comment]
@zepumph new node created and requested doc update added. See https://github.com/phetsims/faradays-law/commit/2b83d6de97d65459743318a08f1144146cf40788.

Assigning back to you to close.

**Comment by zepumph** [comment]
I saw good things in https://github.com/phetsims/faradays-law/commit/ecbd7bacaa64544d3c00e907e7e2e6a8092d5f64, thanks for taking care of that.


I see these lines still in `MagnetNodeWithField`:
```js

      // observers to update inner content of the PDOM Node
      model.magnet.positionProperty.link( () => {
        pdomNode.updatePositionDescription();
      } );

      model.topCoilVisibleProperty.link( showTopCoil => {
        pdomNode.updateNodeVisibility( showTopCoil );
      } );

      model.magnet.orientationProperty.lazyLink( orientation => {
        pdomNode.updateOrientationDescription( orientation );

        utteranceQueue.addToBack( describer.getFlipMagnetAlertText( orientation ) );
      } );

      model.magnet.fieldLinesVisibleProperty.link( showLines => {
        pdomNode.updateFieldLinesDescriptionVisibility( showLines );
      } );
```

besides that `addToBack` call, why not just pass in the model to the PDOMNode and link these PDOM specific functions there? To me that feels a bit more modular. 

Also where ever these calls end up, will you please either add dispose methods, or document that they exist for the lifetime of the simulation.
