### ISSUE TITLE
Add WASD and 123 keyboard interaction details to scene summary in PDOM

### ISSUE THREAD

**Issue by jhung** [phetsims/faradays-law#128]
In the scene summary, where it says: "Move the magnet to play", also add details about the WASD and 123 keys.

Example:
"Move the magnet to play using W A S D or 1 2 3 keys."

**Comment by mbarlow12** [comment]
@jhung, this should be done and can be accessed at:

https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.53/phet/faradays-law_a11y_view.html
or
https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.53/phet/faradays-law_en_phet.html?accessibility

**Comment by jhung** [comment]
Verified. Thanks!
