### ISSUE TITLE
Add 123 keys to alert text on magnet focus

### ISSUE THREAD

**Issue by jhung** [phetsims/faradays-law#129]
When the magnet is focused for the first time, the focus alert should also include details on 123 keys.

Currently:
"Magnet at middle-right of Play Area. W A S D keys moves magnet."

Change to:
"Magnet at middle-right of Play Area. W A S D and 1 2 3 keys moves magnet.

**Comment by mbarlow12** [comment]
@jhung, this should be done and can be accessed at:

https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.53/phet/faradays-law_a11y_view.html
or
https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.53/phet/faradays-law_en_phet.html?accessibility

Do note that the alerts in the above version are not representative of the current implementation. I was just highlighting the content update.

**Comment by jhung** [comment]
It sounds better @mbarlow12. Thanks!
