### ISSUE TITLE
Discussion: What is the coil proximity if magnet collides with coil?

### ISSUE THREAD

**Issue by jhung** [phetsims/faradays-law#130]
Currently, if the magnet collides with the coil, it is described as "in the coil". Visually this doesn't seem to match.

In this special case, would it make sense to describe the magnet in a different way? For example: "just outside the coil" or "next to the coil".

@terracoda do you have any suggestions?

**Comment by terracoda** [comment]
Yes @jhung that's a good approach, an indication of proximity with saying "inside".

Depending on level of detail and level of orientation you want to describe, you could even say, "just above coil", and "just below coil", if it is "just left", or "just right" of coil, that could indicate/hint that the magnet is lined up with the opening.

**Comment by jhung** [comment]
Taking this a little further, perhaps saying that the magnet is "touching top-right of 4 loop coil". It gives information about its location relative to the coil, as well as the special circumstance.

So currently it says:
> "Magnet at center of Play Area. In 4-loop coil."

Change to:
> "Magnet at center of Play Area. Touching top-right of 4-loop coil."
or maybe even shorter
> "Magnet at center of Play Area. Touching 4-loop coil."

Grammatically "Touching top-right of 4-loop coil" is a bit awkward, but it's clear as to what is being referenced.

@terracoda What do you think?

**Comment by terracoda** [comment]
@jhung, I think you want to go with something more conversational, something that might engage questioing, "oh I just bumped into the magnet,what happens if I get inside?"

I think you want just enough orientating information without too much. Just think, "less is more" at every opportunity ;-)

**Comment by emily-phet** [comment]
@jhung If this only happens when magent 'bumps into' coil, that means that the magent and coul are 'touch' and that there would be a corresponding 'bonk' sound. I'm not sure it's necessary to repeat "center of play area" each time...with the bonk users will know something interesting has happened and will probably want feedback immediately about what happened.

How about something like "Touching {top/side/bottom} of 4 loop-coil". I think detail of 'top-left' or 'top-right' is something that could be inferred from further exploration.

**Comment by terracoda** [comment]
@jhung, sorry, I did not follow-up with example. 

I agree with @emily-phet's example. The user might only hear the "center of play area" when they pass above or blow the coils without touching them, unless the position of the coil/coils is described explicitly and statically somewhere else, in which case the user might only need to know when they are below or above a coil, or right or left of one. If they are touching one of the coils or near one of them, they should know perhaps from some other description that they are in the center of the Play Area.

**Comment by jhung** [comment]
@emily-phet and @terracoda - Great points. I will file some new issues to address the verbosity and redundancy of the text description and text alert when in / around / touching the coil.

**Comment by emily-phet** [comment]
This sim's description will be re-designed at a future date. When that's done, we'll review all past issues related to description.
