### ISSUE TITLE
If only 4 loop coil is showing, the light bulb circuit description should be a sentence and not a list

### ISSUE THREAD

**Issue by jhung** [phetsims/faradays-law#133]
If only the 4 loop coil is showing, the light bulb circuit description should be a sentence instead of a list because it doesn't have enough items for a useful list.

Currently, if both Volt meter and 4 loop coil are showing, the description reads:

> In a circuit are a:
> * 4 loop coil
> * Voltmeter

Instead this should be:

> In a circuit are a light bulb, 4 loop coil, and a voltmeter.

However, if just the 4 loop coil, the description reads properly without a list.

**Comment by terracoda** [comment]
@jhung, I would suggest simplifying the phrasing for this. Starting with "In a circuit are a...", is  complex phrasing. I realize, I suggested this based on the description in Ohm's Law, but in that sim the elements of the circuit have important changing parameters values. In this sim, the circuit is a bit more static. You just add and remove things from it.

For comparison with Ohm's Law I describe what makes up the circuit and then have a list of the changing parameters that change during interaction:

**The Circuit**
A pair of wires connect a resistor to a series of batteries. 
In circuit, 
- batteries supply {{4.5 volts}} 
- resistor shows {{a medium amount of impurities}}
- {{small arrows}} indicate a current flowing clockwise at {{5.0 millamps}}

In Faraday's Law, one just adds and removes things from the circuit, so simple might work, though a list could potentially also work, though I would go with one or the other not both.

**Light bulb circuit**
- In circuit, volt meter connects to light bulb. {{Two wires}} connect light bulb to {{a 4-loop coil}}.
- In circuit, volt meter connects to light bulb. {{Two split wires}} connect light bulb to {{two coils, a 2-loop coil and a 4-loop coil. 2-loop coil is just above 4 loop coil}}.

**without the voltmeter**
- In circuit, two wires connect light bulb to {{a 4-loop coil}}.
- In circuit, two split wires connect light bulb to two coils, {{a 2-loop coil}} and {{a 4-loop coil}}. {{2-loop coil is just above 4 loop coil}}.

There could still be some wordsmithing to get the phrases just right, and in the best order for the relevance of the items. For example, you could put volt meter at end if necessary.

Other possibilities:

**Light bulb circuit**
- {{Two wires}} connect light bulb to {{a 4-loop coil}}. {{A volt meter is connected to light bulb.}}
- {{Two split wires}} connect light bulb to {{two coils, a 2-loop coil and}} {{a 4-loop coil}}. {{2-loop coil is just above 4-loop coil.}} {{A volt meter connects to light bulb.}}

**And again, without the voltmeter**
- {{Two wires}} connect light bulb to {{a 4-loop coil}}.
- {{Two split wires}} connect light bulb to {{two coils, a 2-loop coil and}} {{a 4-loop coil}}. {{2-loop coil is just above 4-loop coil.}}

**Comment by terracoda** [comment]
@jhung, have you asked @ariel-phet if it is necessary to describe the details of the circuit, for example, that there are two wires.

**Comment by terracoda** [comment]
Oh, and I just looked at the A11y View and there is another string that was not mentioned in your original post:

- "The coil is open on the left and right, large enough for the bar magnet can pass through."

I guess that would need to be worked in, unless you were planning on dropping it. Sorry, I missed that.

**Comment by jhung** [comment]
Looks good! One change...

Currently:
"In circuit are a light bulb, a 4 loop coil, and a voltmeter." (1 coil)
"In circuit are a:" (2 coils)

Change to:
"The circuit has a light bulb, a 4 loop coil, and a voltmeter." (1 coil)
"The circuit has a:" (2 coils)

**Comment by jhung** [comment]
No longer applicable with revised designs. Closing this issue.
