### ISSUE TITLE
Changes to bar magnet polarity PDOM description

### ISSUE THREAD

**Issue by jhung** [phetsims/faradays-law#134]
If just 4-loop coil showing, the bar magnet polarity description should be a sentence instead of a list. 

Currently:

```
Magnet polarity:
* North pole on the left
* South pole on the right
```

Should be:
```
North pole on left, south pole on right.
```

If both coils showing, the bar magnet polarity description should be part of the list instead of a separate one.

Currently:

```
The bar magnet is:
* at the middle-right of the Play Area.
* Far from 4-loop coil.
* Far from 2-loop coil.

Magnet polarity:
* North pole on the left
* South pole on the right
```

Should be:
```
The bar magnet is:
* at the middle-right of the Play Area.
* Far from 4-loop coil.
* Far from 2-loop coil.
* North pole on the left
* South pole on the right
```

**Comment by terracoda** [comment]
@jhung, I think it might just be a typo, but you always want to use the same exact strings wherever possible to describe the same thing, and possibly the same structure, too.

**What do you think of this:**
**With 1 coil:**
- Bar Magnet, web application. At {{middle-right of Play Area}}, {{far from 4-loop coil}} with {{north pole left, and south pole right}}.

"Bar Magnet" comes from accessible name on focus, and then the description in a paragraph.
Paragraph: {{relevant position if needed}}, {{proximity to coil}}, {{polarity of magnet}}.

**With 2 coils:**
- Bar Magnet, web application. At {{middle-right of Play Area}}, {{far from 4-loop coil}}, {{far from 2-loop coil}} with {{north pole left, and south pole right}}.

As we discussed the other day, you could possibly get rid of the {{relevant position}} description, and just rely on robust proximity-to-coil(s) descriptions, to ensure there is always clear orientation with the coil or coils.

**Comment by jhung** [comment]
@terracoda I'm concerned about making sentences too long. I think we should go with how it is right now and see what testing reveals.

@mbarlow12 it looks good. Closing this issue.

**Comment by terracoda** [comment]
@jhung, we can discuss. Just keep in mind what you think is the essential information a user needs on focus or with a grab button once they activate the grab button. The information on focus can be different than what happens once they start moving the magnet
