### ISSUE TITLE
I do not hear Bar Magnet's name on Focus

### ISSUE THREAD

**Issue by terracoda** [phetsims/faradays-law#136]
In latest version on master, I do not hear the Bar Magnet's accessible name on Focus. I only hear, "Web Application." This is using Safari and Voice Over.

<img width="1105" alt="screen shot 2018-09-24 at 10 58 25 am" src="https://user-images.githubusercontent.com/1902116/45954918-fd6e9200-bfe8-11e8-8049-9dc98f5a51a2.png">

**Ah, I see the problem:**
<img width="807" alt="no-accessible-name" src="https://user-images.githubusercontent.com/1902116/45955131-ad43ff80-bfe9-11e8-8863-af6adb0abf24.png">
The focusable empty `div` representing the Bar Magnet interaction has no associated accessible name either through `aria-label`, or `aria-labelledby`.

In this case, I would suggest trying `aria-labelledby` first as there is an `h3` already in the PDOM representing the name of the magnet.

``` html
<h3 tabindex="-1" id="label-4-60-190">Bar Magnet</h3>
...
<div tabindex="0" id="4-60-190-233" role="application" aria-labelledby="label-4-60-190"></div>
```

I would also recommend trying `aria-roledescription`. We used `aria-roledescription=move in four directions` in Friction. The attribute is only currently supported by Voice Over, but it really makes the interaction sound better, as "move in four directions " is uttered instead of the technical phrase, "web application".

**Comment by terracoda** [comment]
Tagging @jhung and will assign to @mbarlow12.

**Comment by terracoda** [comment]
@mbarlow12, I am marking as top priority, so @zepumph can do #137 near the end of his day.

It's not a complete show stopper if this issue is not fixed.

**Comment by mbarlow12** [comment]
@terracoda Thanks for catching that one. The `aria-labelledby` and `-roledescription` have both been set and sound like they're working properly. Let me know if there's anything else before closing.

**Comment by terracoda** [comment]
@mbarlow12, sounds great!
Thanks for getting to this on short  notice!

On focus (with Voice Over), I hear: "Bar Magnet, move in four directions" and I often I also hear it's initial description (position and interaction instructions).

Sounds great! Thanks @mbarlow12!
