### ISSUE TITLE
Review Studio

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-law#143]
After numerous changes, including adding Emitters, will need to be re-reviewed in Studio.  This may be good to do as a team.  This came from #107

**Comment by samreid** [comment]
Now that we have a tree view in Studio, we may wish to re-open this to a Faraday's Law PhET-iO design meeting.  We will also want to select the featured elements.  On hold until we resume work on this sim.

**Comment by zepumph** [comment]
Closing this, as a subset of work to be done in https://github.com/phetsims/faradays-law/issues/158
