### ISSUE TITLE
With Voiceover, when moving focus off bar magnet and back on, magnet is announced incorrectly

### ISSUE THREAD

**Issue by jhung** [phetsims/faradays-law#144]
If you move focus off then back on the bar magnet, Voiceover will say: "You are currently on a move in four directions..."

Looking at the markup, it seems to be picking up the `aria-roledescription` from the PDOM.

To reproduce:

1. Load Faraday's Law: https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.53/phet/faradays-law_en_phet.html?accessibility
2. Turn on Voiceover.
3. Tab focus on the bar magnet.
4. Voiceover will say:

"Bar magnet, move in four directions."
"Magnet at middle-right of play area. Use W A S D and 1 2 3 keys to move magnet."
"You are currently on a move in four directions..."

I have not verified this issue with Windows screen readers.

**Comment by mbarlow12** [comment]
This is pretty strange behavior since the `aria-labelledby` attribute is set to the Bar Magnet heading element. @terracoda have you seen anything like this before? I'm not on my mac at the moment, so I'll have to test later this evening.

**Comment by terracoda** [comment]
@mbarlow12, that extra text is VoiceOver's built in help. You can turn that off in settings (I turn it off).

That is the correct description, aria-roledescription, "move in four directions"  replaces "web application" on this custom type of object.

**Comment by mbarlow12** [comment]
@jhung after https://github.com/phetsims/faradays-law/issues/144#issuecomment-430243734, am I ok to close this issue?

**Comment by jhung** [comment]
@terracoda thanks for checking that.
@mbarlow12 yes. I'll resolve this now.
