### ISSUE TITLE
Improve alerts in FL?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/faradays-law#146]
In review of https://github.com/phetsims/scenery-phet/issues/405 @mbarlow12 said
> FL appears to be working as it was written (which is pretty sub-optimal).

I am curious about what is sub-optimal with alerts in this sim. @mbarlow12 is the issue there there are still too many alerts during interaction? I played with the sim and saw this behavior of alerts in the a11y-view, I am getting the final alert at the end of interaction, which seems OK:
![2bc11fcadf04273407ebeca107b5211b](https://user-images.githubusercontent.com/6396244/48521913-8ca76180-e844-11e8-97dc-f83bee0365d1.gif)

But I also didn't explore other interactions.

**Comment by ariel-phet** [comment]
This issue is stale, closing
