### ISSUE TITLE
Failed unit tests: regionTester.getColumn is not a function

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-law#147]
Running http://localhost/faradays-law/faradays-law-tests.html yields:

Source: | TypeError: regionTester.getColumn is not a function     at Object.assert (http://localhost/faradays-law/js/faradays-law/view/MagnetRegionsTests.js?bust=1543641891504:40:32)

I'm not sure who will be best to assign, so I'll start with @jessegreenberg @mbarlow12 and @zepumph.

**Comment by jessegreenberg** [comment]
@mbarlow12 is the author of this file and has been working on a11y descriptions in this sim, @mbarlow12 can you please take a look?

**Comment by mbarlow12** [comment]
My apologies. Some of those tests are obsolete now. I made the updates so that test are all passing, though it's a pretty ineffective suite. I'm happy to remove it if we think it'd be preferable.

**Comment by samreid** [comment]
Some tests are better than no tests!  I vote keep the remaining tests.  Anything else before closing?

**Comment by mbarlow12** [comment]
Sounds good @samreid . Should be good to close.
