### ISSUE TITLE
Edge case when magnet at center

### ISSUE THREAD

**Issue by zepumph** [phetsims/faradays-law#148]
I was playing with the really cool keyboard nav just now (it works very well I think). I found a bit of an edge case. Perhaps the "center" definition varies for the magnet projected on the edge and the directional arrows. 

![image](https://user-images.githubusercontent.com/6856943/49839409-626d9480-fd5b-11e8-93b5-6484791a6bcd.png)

I know that this sim isn't in active a11y development but I figured I'd still log the issue. @mbarlow12 over to you. Please feel free to just unassign yourself, but I wanted you to have a look in case it was an easy or duplicated issue, since potentially you are still freshish on the stuff.

**Comment by mbarlow12** [comment]
Sorry for getting to this so late, and thanks for pointing it out. There was a small discrepancy in the magnet position checks between the jump listener and arrow node displays. Fixed and ready for review.

**Comment by zepumph** [comment]
Not a worry, it looks good.
