### ISSUE TITLE
Is the sign of voltage incorrect?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/faradays-law#150]
A teacher wrote to phethelp inquiring about the sign of the voltage:

>Hi Phet,
>
>You have some excellent simulations on your website. My students certainly appreciate all the work that has gone into them.
>
>I just had one small concern. I believe the direction of the current indicated in the Faraday’s Law Simulation may be the opposite direction to what it is meant to be. Could you please double check this one?
>![image](https://user-images.githubusercontent.com/8419308/55206778-c459e900-51e8-11e9-9217-3a4c017c453a.png)
>
>This is a small excerpt from Heinemann Physics 3&4  4th Edition p118.
>![image](https://user-images.githubusercontent.com/8419308/55206793-cf147e00-51e8-11e9-9c8d-b5fd320a31bc.png)

Recreating the user's text case in the legacy version and the 1.0.0 version of HTML5, the needle will deflect towards the positive voltage, as described in the textbook. It seems like this was bug was introduced sometime after 1.0.

@ariel-phet can you take a look? If our physics is indeed wrong here (which it seems to be) we should probably get out a maintenance release ASAP.

**Comment by arouinfar** [comment]
@oliver-phet just received another email from an AP physics student reporting the same issue.

> Hi,
>
>I was using the Faraday's Law simulation in an AP Physics C E/M course and using it to verify predictions about induced current direction in the four coils (not the four coil and two coil setting) based on Lenz's Law, I was getting opposite behavior to what I expected. Here is what I noticed and expected:
>
>Noticed: If I took the bar magnet in a N-S arrangement and moved it into the coils of wire, (with N end entering from the right side of the coil), the dial on the voltage meter was deflected to the left, to a negative voltage reading. See screenshot below.
![image](https://user-images.githubusercontent.com/8419308/55840502-d5f49800-5ae8-11e9-901b-ced81d5a894a.png)
>
>Expected: If I took the bar magnet in a N-S arrangement and moved it into the coils of wire, there would be an increasing magnetic flux magnitude caused be an increasing B-field magnitude to the left, and according to Lenz's Law, a current would be induced in the coils that attempted to counteract this. This would be accomplished by an induced current that produced a B-field to the right, which by a RHR should occur with a counterclockwise conventional current through the coils when viewed from the +x axis. Looking at the simulation, it looks like this is equivalent to conventional current moving from the + side of the voltage meter to the - side of the voltage meter. If this were occurring, I would expect the + side of the voltage meter to be at a higher potential than the - side, which I would think would be consistent with a positive voltage reading. This seems contrary to what I noticed.
>
>My dad, who is a professor of electrical engineering, and my instructor both agree with my expectations of how the simulation should behave. Could you please help me understand why the simulation is behaving opposite of what all of us would expect?
>
>Thanks.

**Comment by ariel-phet** [comment]
@arouinfar 

Probably the simplest way to answer this question is to first agree on which way the voltage should read if the current in the bulb is flowing "right to left" (RTL) or "left to right" (LTR). Current flows from high potential to low potential. So

1. If current is RTL, the voltage should read positive.
2. If current is LTR, the voltage should read negative. 

Lets address the situation presented in comment https://github.com/phetsims/faradays-law/issues/150#issuecomment-481471216

Most of what this student writes is correct. With the North pole of the magnet moving towards the coil, you will have a B field to the right, and that corresponds to current moving counterclockwise when viewed from the +x axis. However, that implies current entering the left side of the coil, and exiting the right side of the coil. Which in the bulb is a LTR current, which should be a negative reading on the voltmeter. 

So the student has the direction of the current in the bulb incorrect (but everything else right). The perspective of the coils is a bit funky, and the way the wires from the coil ends enter and leave the coil I think can lead to some confusion.

So to me, the published sim is correct. This seems to jive with the change we made for #65  - but perhaps we should consider current arrows for this simulation (much like in CL:B) to help alleviate confusion? It even takes me a bit to convince myself I have everything right.

**Comment by arouinfar** [comment]
@ariel-phet I still think the sim is incorrect here.

Based on on the direction of the induced current, the left side of the coil is the positive end. The positive probe of the voltmeter is attached to the same end, so the needle should deflect to the right (positive).
![image](https://user-images.githubusercontent.com/8419308/55844542-fc233380-5afa-11e9-91e7-07b1be4335a7.png)

By comparison, placing the positive probe of the voltmeter on the side of the light bulb connected to the positive terminal of the battery results in a positive voltage reading.
![image](https://user-images.githubusercontent.com/8419308/55844716-ea8e5b80-5afb-11e9-92ac-57fd4ab6a602.png)

**Comment by ariel-phet** [comment]
@arouinfar I need to respectfully disagree here. Notice in the situation you made, the current is flowing left to right. So the proper analogy to the sim would be to have the positive lead of the voltmeter on the right hand side of the bulb(as in the sim). So the voltage should in fact read negative.

![circuit](https://user-images.githubusercontent.com/4051174/55848897-d2bed380-5b0b-11e9-9abe-f51a8bac1f78.PNG)

**Comment by ariel-phet** [comment]
@arouinfar I think you have to be a bit careful about talking about the coil having a positive or negative side...I think it is clearest to think about it as a source of EMF that is driving the current in a certain direction. current flows from high potential to low potential, so I think the bulb seen in the snapshot in the comment above is a good example.

**Comment by arouinfar** [comment]
@ariel-phet thanks for the detailed explanations! Once I traced the induced current around the rest of the circuit, I can clearly see the bulb has an LTR current, resulting in a negative voltage.

I'll reply to the two users who reached out to us with difficulties with the sign of the voltage. 

I also quite like the idea of having a representation for the current, so I'll open up a new issue and work on some mock ups.

**Comment by arouinfar** [comment]
Users have been emailed, and issue for current arrows has been opened. Closing.
