### ISSUE TITLE
Add representation for current direction

### ISSUE THREAD

**Issue by arouinfar** [phetsims/faradays-law#152]
Recently, two users contacted phethelp with concerns that the sign of the voltage was incorrect, see #150. The sim's behavior is correct, however previous versions of the simulation the sign of the voltage actually was incorrect, see #65.

In #150 @ariel-phet wrote:
> So to me, the published sim is correct. This seems to jive with the change we made for #65 - but perhaps we should consider current arrows for this simulation (much like in CL:B) to help alleviate confusion? It even takes me a bit to convince myself I have everything right.

I think this is an excellent idea. Showing the **conventional** current direction would make the sign of the voltage much clearer. After all, the RHR is used to determine the direction of the conventional current. If we would want to show both the electron and conventional currents, I think the conventional current would be a more natural default. Though I would be curious to hear @ariel-phet's thoughts.

Here are some quick mockups
![image](https://user-images.githubusercontent.com/8419308/56324183-6e170080-612b-11e9-9c28-89db45d19ac8.png)
![image](https://user-images.githubusercontent.com/8419308/56324234-8edf5600-612b-11e9-9599-1931831a7f43.png)

**Comment by ariel-phet** [comment]
@arouinfar yes, I agree, conventional current would be the preferred default to show. I think showing the electron flow direction in this particular simulation would confuse the issue (I would not even have it as an option) since, as you point out, the RHR uses conventional current.

**Comment by arouinfar** [comment]
Thanks @ariel-phet. Any thoughts about the mockups?

The close vertical spacing of the wires makes it a bit tricky, so I've had to stagger the arrows in the fist mockup. I think the second mockup does a better job of emphasizing the current direction through the bulb, but the space to show the arrows is much more limited.

**Comment by ariel-phet** [comment]
@arouinfar what about "curvy arrows" around the bends?

**Comment by oliver-phet** [comment]
Another user emailed:
> I recently went to the Faraday's Law simulation on HTML5 and was curious if it's at all possible to add back the option to "show electrons" that was in the Java version called faraday_en.jar. Simulating the charge movement really helps students to visualize this phenomena at a particle level.

**Comment by arouinfar** [comment]
The legacy version of [Faraday's Law](https://phet.colorado.edu/sims/faradays-law/faradays-law_en.html) does not show electrons. It looks like the user is referring to [Faraday's Electromagnetic Lab](https://phet.colorado.edu/en/simulation/faraday) which is a different sim (though related). @oliver-phet can you point the user to the Java and CheerpJ versions of Faraday's Electromagnetic Lab?

**Comment by oliver-phet** [comment]
My mistake, will do!

**Comment by arouinfar** [comment]
Two more users have recently written to phethelp about the current direction, so we may want to consider adding this representation in the nearish future. Perhaps it could be rolled in with the work currently going on in this sim?

I'll mock up the curvy arrow option soon.

**Comment by jbphet** [comment]
@arouinfar and @ariel-phet - This discussion appears to have died out.  We are planning a re-release of this simulation soon, if you'd like to get this in we should decide and finalize the design very soon.

**Comment by arouinfar** [comment]
We'll be discussing this in design meeting tomorrow, but I've mocked up a few variations on curvy arrows. Here's an example:

![image](https://user-images.githubusercontent.com/8419308/97497299-eae58600-192f-11eb-92c0-9e363e9670a8.png)

**Comment by ariel-phet** [comment]
Would be good to get KP's input here at design meeting - I could see an argument for NOT including the current direction and it being something the student needs to figure out (via the right hand rule or such).

Even if we do decide to pursue this enhancement, it will not be worked on for the upcoming release and would require some work on alternative input/sound for the feature.

**Comment by arouinfar** [comment]
In the 10/29/2020 design meeting we decided not to add this feature.
