### ISSUE TITLE
move a11y strings into main strings json

### ISSUE THREAD

**Issue by zepumph** [phetsims/faradays-law#156]
From https://github.com/phetsims/chipper/issues/795

**Comment by zepumph** [comment]
@jessegreenberg please spot check.

**Comment by jbphet** [comment]
I think @zepumph may have forgotten to assign this issue, so I'm assigning to @jessegreenberg based on the previous comment.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/faradays-law/commit/ffbeac985a31736aafe7b2601bdc5f83dc2e043d looks good and strings are looking good in the a11y view. Closing.
