### ISSUE TITLE
Faraday's Law unit tests load code that references phetioEngine before it is loaded.

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-law#157]
For https://github.com/phetsims/tasks/issues/1035, Faraday's Law unit tests load code that references phetioEngine before it is loaded.

I'll move the phetioEngine dependent code from static space into the tests.  This is a band-aid rather than a surgery.  I don't know what the long term solution will be, but maybe @zepumph can recommend something?

**Comment by samreid** [comment]
Fix committed, @zepumph can you please take a look?

**Comment by zepumph** [comment]
Thanks!

**Comment by zepumph** [comment]
I have done similar stuff in BASE, I feel like this is fine, as it is for tests only, and it fails loudly so you know when you are doing it wrong. I'm not too worried.
