### ISSUE TITLE
Create and integrate coil-related sounds

### ISSUE THREAD

**Issue by jbphet** [phetsims/faradays-law#162]
This is a child issue of #161.

In the 7/14/2020 sound design meeting we decided that the next steps in the implementation of the sound design are to work on creating and integrating sounds for the magnet bumping into the coils - one sound for the upper coil and one for the lower - and a sound for switching between the single- and dual-coil configurations.  The sounds in the sonification wrapper sound design prototype are decent, and @Ashton-Morris will use these as a starting point.

For reference, here's a link to the prototype: https://bayes.colorado.edu/dev/html/phet-io-wrapper-sonification/1.0.0-dev.126/build/phet-io-wrapper-sonification/faradays-law/html/faradays-law-sonification.html.

**Comment by Ashton-Morris** [comment]
I have three variations to try. Two of them have multiples for randomization but you don't need to implement that for now. Just one will do as we feel out which direction we like.

[Sounds will live here](https://drive.google.com/drive/folders/1WHcnidTFlNuX8SmS6jtOl_8_2acf3yfR?usp=sharing)

- coil-bump-option-3-002.mp3
- coil-bump-option-3-002.wav
- coil-bump-option-3-001.mp3
- coil-bump-option-3-001.wav
- coil-bump-option-3.mp3
- coil-bump-option-3.wav


- coil-bump-option-2-002.mp3
- coil-bump-option-2-002.wav
- coil-bump-option-2-001.mp3
- coil-bump-option-2-001.wav
- coil-bump-option-2.mp3
- coil-bump-option-2.wav


- coil-bump-option-1-001.mp3
- coil-bump-option-1-001.wav

**Comment by jbphet** [comment]
We reviewed the list of candidates above in the 7/22/2020 sound design meeting and decided that we'd like something similar to coil-bump-option-3 but with a little bit less of an abrupt attack.  Also, we'll need a higher one and a lower one for bumping into the smaller and larger coils, respectively.  We don't at this point think we need to have multiple variations to choose from randomly - it can be the same sound for each bump into a given coil.

**Comment by jbphet** [comment]
We also will need sounds for switching between the single- and dual-coil configurations.

**Comment by Ashton-Morris** [comment]
[I have tried to lower the attack and have a low and high option now. ](https://drive.google.com/drive/folders/1WHcnidTFlNuX8SmS6jtOl_8_2acf3yfR?usp=sharing)

coil-bump-option-3-low.wav
coil-bump-option-3-high.mp3
coil-bump-option-3-high.wav
coil-bump-option-3-low.mp3

**Comment by Ashton-Morris** [comment]
Also after playing with the current sonified version I realized that the previous sound has completely colorized my thinking on the sound. Currently it sounds like 1.2. 2.1. but with beeps and clicks to me. 

After muting it for a long while I realized that I might be overthinking it a bit. I think we should start with regular radio button sounds first and then see if we feel anything is missing.

**Comment by jbphet** [comment]
We reviewed these sounds at the 7/28/2020 sound design meeting and decided we all quite liked `coil-bump-option-3-low` and `coil-bump-option-3-high` sounds.  They have been integrated into the sim and we did the initial volume adjustment during the meeting.

@Ashton-Morris - I have renamed these sound in GitHub to `coil-bump-low` and `coil-bump-high` in case you need to keep a record of the source files.  Once noted, feel free to close this issue.
