### ISSUE TITLE
Pickup and drop sounds

### ISSUE THREAD

**Issue by jbphet** [phetsims/faradays-law#166]
This is a child issue of #161.

In today's sound design meeting we tried out the standard pickup and drop sounds.  We decided that this sim needs something a bit more "real" sounding, since we have the realistic coil bump sounds.  

We're looking for something that isn't super sophisticated, but has a little bit more of a feeling of "mass" to it.

@Ashton-Morris - please create some candidates in pairs (pickup and release) that we can try out.

**Comment by Ashton-Morris** [comment]
[Here are some metal sounds. Two pickup versions
](https://drive.google.com/drive/folders/1WHcnidTFlNuX8SmS6jtOl_8_2acf3yfR?usp=sharing)
pickup-magnet.wav
put-down-magnet.mp3
put-down-magnet.wav
pickup-magnet-just-metal.mp3
pickup-magnet-just-metal.wav
pickup-magnet.mp3

And here are some references for listening. These are previous non-tonal pickup and drop sounds that we've tried.

previous-pickup-and-grab-sounds.mp3
previous-pickup-and-grab-sounds-001.mp3
previous-pickup-and-grab-sounds-002.mp3
previous-pickup-and-grab-sounds-003.mp3
previous-pickup-and-grab-sounds-004.mp3

**Comment by jbphet** [comment]
The latest sounds have been integrated and I added an "Options" dialog so that we can compare them easily.  We'll review in the 8/11/2020 sound design meeting.

**Comment by jbphet** [comment]
Reviewed these sounds in the 8/11/2020 sound design meeting, here are the thoughts:

- We prefer `pickup-magnet-just-metal` over `pickup-magnet`.  Something about the latter kind of sounded like a pick axe.
- The metallic sounds are almost too real sounding, since that are very real sounds, but picking up a magnet wouldn't really sound like this.  Can these sounds be made a little more "cartoonish"?

@Ashton-Morris will see if he can come up with some sounds along these lines to try out for next week.

**Comment by Ashton-Morris** [comment]
[I have three FM versions to test out here.](https://drive.google.com/drive/folders/1WHcnidTFlNuX8SmS6jtOl_8_2acf3yfR?usp=sharing)

- put-down-magnet-fm-v3.mp3
- put-down-magnet-fm-v3.wav
- pickup-magnet-fm-v3.mp3
- pickup-magnet-fm-v3.wav
- put-down-magnet-fm-v2.mp3
- put-down-magnet-fm-v2.wav
- pickup-magnet-fm-v2.mp3
- pickup-magnet-fm-v2.wav
- put-down-magnet-fm-v1.mp3
- put-down-magnet-fm-v1.wav
- pickup-magnet-fm-v1.mp3
- pickup-magnet-fm-v1.wav

**Comment by jbphet** [comment]
We reviewed the latest (see above) in the 8/18/2020 sound design meeting, and there was a definite collective preference for the fm-v2 and fm-v3 sounds.  For next week, we'd like to eliminate the other sound options for this and try one additional variant: fm-v3 raised either a 5th or an octave, whichever sounds better to @Ashton-Morris when he creates them (or if it's hard to decide, we could add both).

**Comment by Ashton-Morris** [comment]
[I did a fifth and an octave just to me safe
](https://drive.google.com/drive/folders/1WHcnidTFlNuX8SmS6jtOl_8_2acf3yfR?usp=sharing)
- pick-up-magnet-fm-v3-fifth.wav
- put-down-magnet-fm-v3-octave.mp3
- put-down-magnet-fm-v3-octave.wav
- pick-up-magnet-fm-v3-octave.mp3
- pick-up-magnet-fm-v3-octave.wav
- put-down-magnet-fm-v3-fifth.mp3
- put-down-magnet-fm-v3-fifth.wav
- pick-up-magnet-fm-v3-fifth.mp3

**Comment by Ashton-Morris** [comment]
Also it was mentioned to have the voltage max sound once octave higher. I added those files as well.

- voltage-max-octave-higher.mp3
- voltage-max-octave-higher.wav

**Comment by jbphet** [comment]
These sounds are integrated on master along with options for selecting them.  We can review in today's sound design meeting (8/25/2020).

**Comment by jbphet** [comment]
We reviewed these sounds in the 8.25.2020 sound design meeting and settled on the fm-v3-fifth sounds.  @jbphet will remove the other sounds and the dialog options and finalize the code for this.

**Comment by jbphet** [comment]
@Ashton-Morris - I've integrated what we've decided upon for the magnet grab and release sounds.  I've renamed them as follows so that you can keep track of the original source files if desired:

`pick-up-magnet-fm-v3-fifth` -> `grab-magnet`
`put-down-magnet-fm-v3-fifth` -> `release-magnet`

**Comment by jbphet** [comment]
@Ashton-Morris - assigning this to you to make sure that you see the information about the file renames (see the comment above).  You can close once you're aware of the changes.

**Comment by Ashton-Morris** [comment]
Got it
