### ISSUE TITLE
Boundary sounds

### ISSUE THREAD

**Issue by jbphet** [phetsims/faradays-law#167]
This is a child issue of #161.

I did a prototype demo of sound for when the magnet reaches the drag bounds at today's sound design using `generalBoundaryBoopSoundPlayer`.  The consensus was that these sounded a bit too unphysical in this particular context.  For next week we'd like to try the outer boundary sound used in gravity-force-lab.

**Comment by samreid** [comment]
A CT error started showing up in Faraday's Law after https://github.com/phetsims/faradays-law/commit/f16646e2c1aee3908a5d68801fce01bc793b706a

**Comment by jbphet** [comment]
Reviewed and approved in today's sound design meeting.  Closing.
