### ISSUE TITLE
How should the magnet be picked up when using the keyboard?

### ISSUE THREAD

**Issue by jbphet** [phetsims/faradays-law#175]
In some of our published simulations, such as [balloons-and-static-electricity](https://phet.colorado.edu/sims/html/balloons-and-static-electricity/latest/balloons-and-static-electricity_en.html) and [friction](https://phet.colorado.edu/sims/html/friction/latest/friction_en.html), when the user needs to pick something up via keyboard navigation, they do so by tabbing to the desired object and then pressing the space bar.  In other sims, such as [gravity-force-labs](https://phet.colorado.edu/sims/html/gravity-force-lab/latest/gravity-force-lab_en.html), the user can move an object simply by tabbing to it (no space bar press required).  The rule so far seems to be that 2D motion requires the space bar, 1D motion does not, but there may be other factors that affect the decision.

Which approach should we use in faradays-law?

I've published [a dev version ](https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.59/phet/faradays-law_en_phet.html) that includes a no-space-needed way to move the magnet around.  This is based on our early attempts, and there are aspects of the navigation that will clearly need to be modified, but you can try it out to help decide if we want to require the space bar in order to pick up the magnet.

Assigning to @emily-phet and @terracoda for their input, they can reassign as necessary, but it should be assigned back to me for implementation once a decision has been made.

**Comment by jbphet** [comment]
PS: This is a child issue of #174.

**Comment by emily-phet** [comment]
@jbphet 

For Faraday's Law, we'll want the to two-step interaction for selecting and then moving the magnet. 

Other could give a more technical response, but I think this captures the basic idea. As part of support for non-visual access, the magnet is implemented as a custom object. Custom objects are by definition not part of the standard set of interactions, and thus must come with additional information we provide to the user (through screen readers) to let them know how to use the custom object. When a user gets to the object, we've found it can be too much to provide this at first - it's better to have the object as a button to start, and then once pressed, we provide the user with further info on how to interact. Imagine exploring an unknown space filled with familiar objects and one unfamiliar one. You might explore the familiar ones first, and that's what we saw with some visually impaired learners. In this case, the magnet is the most important thing, so having it start as a button gets people interacting with it early. We are exploring situations where this two-step interaction for custom objects may not be necessary, but for Faraday's Law let's follow the pattern established in BASE and Friction. 

Note  - we'll need information about the interaction to appear visually when you select the magnet. Please let me know if you need artwork drawn for this, or if you can just use BASE as an example.

**Comment by jbphet** [comment]
> Note - we'll need information about the interaction to appear visually when you select the magnet. Please let me know if you need artwork drawn for this, or if you can just use BASE as an example.

I'll start with what was used for BASE and we can go from there.

**Comment by jbphet** [comment]
Since we have a clear answer to this question, I'm going to close it and implement the changes under #174.
