### ISSUE TITLE
Voltmeter should be off by default

### ISSUE THREAD

**Issue by jbphet** [phetsims/faradays-law#180]
During today's sound design meeting it was revealed that a decision had been made a while back to have the voltmeter off by default.

**Comment by jbphet** [comment]
For reference, the issue under which the ability to hide the voltmeter was originally added was https://github.com/phetsims/faradays-law/issues/106.

**Comment by jbphet** [comment]
Implemented.

@ariel-phet - I just thought I'd have you take a look at it, or assign another designer to do so, with this change in place.  It looks okay upon startup with this change in place, but a little "off balance" to me, and I was thinking that perhaps we should move the light bulb up a bit to create more of an initial symmetry.  We'd leave the voltmeter where it is and just shorten the wires.  I'm open to other ideas too, and okay with just leaving it as is.

**Comment by ariel-phet** [comment]
@jbphet yes, I think that is a good idea, to move the bulb up and shorten the voltmeter wires. I would do something like the following (also moving the bottom coil up a bit and such, it looks quite close to the scene selection buttons)

![Capture](https://user-images.githubusercontent.com/4051174/94471704-d4a8a680-0186-11eb-91d4-5a2d813c18e7.PNG)

**Comment by jbphet** [comment]
I've adjusted the layout based on the recommendation above.  I didn't go quite as high with the light bulb as is shown because I felt like it crowded the voltmeter when it was on.  @ariel-phet - please review the version on master and let me know if you think further revisions are required.  If so, let's set up a "pixel polishing" design meeting where we can tweak it in real time, since that seems most time efficient.

**Comment by ariel-phet** [comment]
All looks good to me @jbphet

**Comment by jbphet** [comment]
Cool, thanks for checking it out.  Closing.
