### ISSUE TITLE
Visual cue arrows "flickering" bug

### ISSUE THREAD

**Issue by zepumph** [phetsims/faradays-law#183]
Discovered while working on visibleProperty stuff over in https://github.com/phetsims/scenery/issues/1046.

The magnet arrows go away correctly but are shown again on the next press, only to be hidden when dragged.

Steps to reproduce:
1. Faradays law sim open
2. click and drag and let go of the magnets, now no more arrows are visible.
3. click and don't move the mouse at all, arrows toggle visible again until you start to drag again.

I know that @jbphet has been in this sim, so I'll start there, but feel free to reassign.

**Comment by jbphet** [comment]
This behavior is in active development at the moment, see https://github.com/phetsims/faradays-law/issues/174, and the problem described will be fixed as part of that effort, so there is no need for a separate issue.  Closing.
