### ISSUE TITLE
Create sound features video

### ISSUE THREAD

**Issue by emily-phet** [phetsims/faradays-law#187]
@BLFiedler you can work on this as we discussed at the start of the quarter (in a batch towards the end of the quarter). Just making the issue here to keep track.

**Comment by BLFiedler** [comment]
Script in progress link: 

https://docs.google.com/document/d/1XYNpCEW0Pq2GQdrp6VNKaMdRK1k2ZDzr8uzdk0ceDuo/edit?usp=sharing

**Comment by BLFiedler** [comment]
This has been checked over by @jbphet and is set to be recorded next week in a batch with RaP and W:I.

**Comment by BLFiedler** [comment]
Published - see sim page: https://phet.colorado.edu/en/simulation/faradays-law
