### ISSUE TITLE
Updating interview list

### ISSUE THREAD

**Issue by emily-phet** [phetsims/faradays-law#190]
@BLFiedler 
can you reach out to Taliesin about how she does this?

**Comment by terracoda** [comment]
There should be a spreadsheet in each sim folder.
If not one has to be created.
I usually copy one from another sim folder.

**Comment by terracoda** [comment]
@BLFiedler, I copied a blank spreadsheet from GFL over to FL.
It is in the root of the Multi-modal Features folder.

**Comment by terracoda** [comment]
@BLFiedler, in addition to filling out the interview spreadsheet for the protocol on the research drive, you would put the minimal information in the the spreadsheet in the sim folder, ensuring you note under what protocol the interview was done. 

The idea is that there is one place that records all the interviews done for a sim.

**Comment by terracoda** [comment]
You can see the spreadsheet doe GFLB as an example. That sim has many interviews listed from diverse protocols.

**Comment by BLFiedler** [comment]
updated w/ three interviews done so far
