### ISSUE TITLE
Screenshots need to be updated with upcoming publication 

### ISSUE THREAD

**Issue by emily-phet** [phetsims/faradays-law#191]
Visual design has changed - voltmeter has checkbox. Screenshots need to be updated. 

Not sure who does this... @KatieWoe is this something QA can do?

**Comment by KatieWoe** [comment]
Yes, we can. Let me know what version you want me to take the screenshots with.

**Comment by jbphet** [comment]
@KatieWoe - You can use https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.64/phet/faradays-law_en_phet.html, which was created today (10/27/2020) and we don't expect to modify the visual design any more than we already have.

**Comment by KatieWoe** [comment]
Some screenshots were hard to reproduce, so I made some options (for screenshot-alt1). I also made a screenshot-alt2 to showcase turning off the voltmeter. @arouinfar, @ariel-phet, or @emily-phet please approve these and let me know which alt1 you prefer.

**Comment by KatieWoe** [comment]
Main screenshot.
![faradays-law-screenshot](https://user-images.githubusercontent.com/41024075/97486317-e5347400-1920-11eb-8d90-a3e75c01046b.png)

**Comment by KatieWoe** [comment]
My suggestion for alt1.
![faradays-law-screenshot-alt1](https://user-images.githubusercontent.com/41024075/97486358-f3829000-1920-11eb-9efb-e0709bbc2fb1.png)
Other possibility for alt1.
![Screenshot Capture - 2020-10-28 - 12-35-33](https://user-images.githubusercontent.com/41024075/97486395-fd0bf800-1920-11eb-819d-d271166f52be.png)

**Comment by KatieWoe** [comment]
Proposed alt2.
![faradays-law-screenshot-alt2](https://user-images.githubusercontent.com/41024075/97486429-0ac17d80-1921-11eb-9814-f599092e1beb.png)

**Comment by arouinfar** [comment]
Thanks @KatieWoe! I like the first option for alt1 and your proposed alt2.

You might want to wait on committing them until #155 is resolved, however.

**Comment by KatieWoe** [comment]
Ok. Let me know when.

**Comment by arouinfar** [comment]
@KatieWoe we decided not to include #155 in the upcoming release, so I think you can take care of the screenshots anytime.

**Comment by KatieWoe** [comment]
Screenshots in the above commit.

**Comment by emily-phet** [comment]
@KatieWoe Sorry for not reaching out to you yesterday. I saw @arouinfar responding, and she's actually the best person to respond about these screenshots. Whatever she preferred is good to me. 

Closing this issue now.
