### ISSUE TITLE
Performance issues on Mac for Safari when moving the magnet

### ISSUE THREAD

**Issue by DevonQui** [phetsims/faradays-law#193]
**Test device**
MacBook Pro

**Operating System**
Catalina 10.15.1 

**Browser**
Safari 

**Problem description**
This is for https://github.com/phetsims/QA/issues/568
When moving the magnet, the movement is very choppy and only uni-directional. This is in contrast to running this simulation in Chrome where the movement is very smooth and diagonal movement is allowed by combining the arrow keys. Combining arrow keys to move diagonally in Safari doesn't seem like it's supported. 

**Steps to reproduce**
1. Open Safari, and open the simulation in Safari
2. Enable the keyboard shortcuts by pressing tab (or option-tab)
3. Click space or tab when the magnet is highlighted to allow for keyboard control of the magnet's position
4. Move the magnet normally and notice the lag between switching directions
5. Also try to combine horizontal and vertical keyboard arrows to try and produce diagonal movement (you cannot)

**Visuals**
Here's a video of a comparison between sim performance on Safari and on Chrome.
https://drive.google.com/file/d/1ABvrc0mU1kx2W7ehmnSAXUI73gZ1WfAn/view?usp=sharing

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Faraday's Law‬
URL: https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.65/phet/faradays-law_en_phet.html
Version: 1.4.0-dev.65 2020-10-27 23:56:15 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Language: en-US
Window: 1440x812
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by DevonQui** [comment]
The performance on all other aspects of the simulation are fine, it just seems to be affecting the movement of the magnet.

**Comment by jbphet** [comment]
First of all, let me address the part of the problem description that says:

> Also try to combine horizontal and vertical keyboard arrows to try and produce diagonal movement (you cannot)

After a fair amount of debugging, I came across a section of code in `KeyboardDragListener` that says this:

```
    // Prevent a VoiceOver bug where pressing multiple arrow keys at once causes the AT to send the wrong keycodes
    // through the keyup event - as a workaround, we only allow one arrow key to be down at a time. If two are pressed
    // down, we immediately clear the keystate and return
    // see https://github.com/phetsims/balloons-and-static-electricity/issues/384
```

It appears that because of https://github.com/phetsims/balloons-and-static-electricity/issues/384, we intentionally disallow two arrow keys being down at the same time, so in essence, diagonal movement of the magnet isn't allowed on Safari.

**Comment by jbphet** [comment]
I've got a theory about the part of the problem description that says

> Move the magnet normally and notice the lag between switching directions

I have a MacBook Air running OSX 10.12.6 and Safari 12.1.2.  If I move the magnet back and forth and am careful to release the previously pressed arrow key before pressing another one, I do not notice any lag in the magnet's change of direction.  However, if I do not release the previously pressed key first, I do notice such a lag.  This is a result of the same workaround code described in the comment just above - the code is triggering an interrupt to avoid the issue with Safari, and so it has to wait until the arrow key repeats before the new motion starts.

Unless something has changed that would allow us to remove the workaround for VoiceOver, I don't think that there is an easy solution for this, so I would recommend that we just live with it.  I don't find it to be a particularly troublesome behavior.

**Comment by jbphet** [comment]
@emily-phet, @Ashton-Morris, and I discussed this in today's weekly a11y meeting for Faraday's Law, and they agree that we need to leave the workaround for VoiceOver in place and should just live with the current behavior.  Closing.
