### ISSUE TITLE
Command + arrow key causes buggy movement with keyboard nav.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/faradays-law#199]
**Test device**
MacBook Air
**Operating System**
MacOS 10.15.7
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/568. May be more general.
If you grab the magnet with keyboard nav, then press command (on Mac) + an arrow key, the magnet moves all the way to the side in that direction and continues to push that way, even if you only tapped the key. For instance, if you press down while doing this, you will be unable to move the magnet up for a bit, or you can move it up and when you let go it moves back down. The exact behavior seems to vary a bit.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Faraday's Law‬
URL: https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.65/phet/faradays-law_en_phet.html
Version: 1.4.0-dev.65 2020-10-27 23:56:15 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
Language: en-US
Window: 1214x685
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jbphet** [comment]
@jessegreenberg - I'm going to leave this one to you initially, please let me know if it is some sort of modification to the keyboard drag handler that needs to be made.

**Comment by jessegreenberg** [comment]
I was able to verify this behavior. When this happens, we are not receiving a key up event for the arrow key when it is released so the sim thinks it is still down. It seems that this is a general problem, see http://web.archive.org/web/20160304022453/http://bitspushedaround.com/on-a-few-things-you-may-not-know-about-the-hellish-command-key-and-javascript-events/ and http://web.archive.org/web/20160304022453/http://bitspushedaround.com/on-a-few-things-you-may-not-know-about-the-hellish-command-key-and-javascript-events/

> As soon as the cmd key is pressed, it takes all the attention of the keyup event, which will purely and simply forget other keys exist. It is therefore impossible to count reliably how many keys are pressed at the same time as soon as the cmd key enters the equation, which is a big problem when you're looking to capture complex key stroke combinations (many modifiers + many "regular" keys).

**Comment by jessegreenberg** [comment]
I would recommend that we prevent keyboard movement when the command key is down to prevent allowing this from happening. Furthermore, command + arrow key is the key command to go back a page so I think that is what it should do instead.

**Comment by jessegreenberg** [comment]
Fix made in the above commit, @KatieWoe can you please verify?

**Comment by KatieWoe** [comment]
Looks fixed on master.

**Comment by jessegreenberg** [comment]
Thanks!
