### ISSUE TITLE
Magnet jumps to the side of wire coil when sim is slow

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/faradays-law#200]
**Test device**
MacBook Air
**Operating System**
MacOS 10.15.7
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/568. Only reproduced when `?speed=.1` which is not a normal use case (I was using it to lengthen the time the light was active for an unrelated test) and so this may not need to be addressed. But I'm making an issue in case it is indicative of a larger issue.
When using keyboard nav to move the magnet, if it rubs against the wire coil, it seems to jump to the left side of the coil.
**Steps to reproduce**
1. Set speed to be slower with a query parameter.
2. Use keyboard nav to move the magnet above the wire coil
3. Press down and right arrow keys to rub magnet against coil

**Visuals**
![jumpingmagnet](https://user-images.githubusercontent.com/41024075/97929201-de916c80-1d25-11eb-9e82-44ed29f5a029.gif)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Faraday's Law‬
URL: https://phet-dev.colorado.edu/html/faradays-law/1.4.0-dev.65/phet/faradays-law_en_phet.html?speed=.1
Version: 1.4.0-dev.65 2020-10-27 23:56:15 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
Language: en-US
Window: 1214x685
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jbphet** [comment]
I don't think that this is indicative of another issue, and if it can't be reproduced at normal speed, it doesn't seem to me like it is worth much investigation time.  I'll leave it open for a while and may take a quick look before publication, but more likely will just close.

**Comment by jbphet** [comment]
@KatieWoe - I believe that this should be fixed by some work done for #195.  Please have QA test on master.

**Comment by KatieWoe** [comment]
Looks good in master.

**Comment by KatieWoe** [comment]
Looks good in rc.1
