### ISSUE TITLE
User suggestion: rotate magnet

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/faradays-law#202]
> Can I suggest an additional control in the Faraday’s law simulation? Allow the user to rotate the magnet 90 degrees, so the field lines are primarily vertical. This will help students see that it is only the perpendicular component of the field that contributes to the flux…

@arouinfar can you comment on this suggestion?

**Comment by arouinfar** [comment]
This is an interesting suggestion, but it's not a change we will make. It would require significant design changes (coil diameter, UI control for magnet orientation, lots of implications for sound and description) and doesn't serve the primary learning goals of this simulation.

**Comment by oliver-phet** [comment]
Thanks, @arouinfar. Email to user sent!
