### ISSUE TITLE
Auto-slide doesn't stop if magnet grabbed while moving

### ISSUE THREAD

**Issue by jbphet** [phetsims/faradays-law#203]
If the user initiates an auto-slide using keyboard navigation and then uses the mouse to grab the magnet, the animation doesn't cancel and odd behavior results.

**Comment by muedli** [comment]
This looks fixed in 1.4.0-rc.1, but I'll let @KatieWoe make the final call.

**Comment by KatieWoe** [comment]
This does look fixed. I did notice an odd behavior where, if you start using mouse during auto slide to cancel keyboard nav, but don't actually click the magnet, auto slide will continue. If you click the magnet it will cancel.
![clickoutslide](https://user-images.githubusercontent.com/41024075/101225801-aac0a400-364f-11eb-8733-ec10f24f927f.gif)
@jbphet if this is alright, then feel free to close.

**Comment by jbphet** [comment]
@KatieWoe - Yes, the behavior you describe in the comment immediately above is intentional.

Closing.
