### ISSUE TITLE
1,2, and 3 buttons may become unresponsive if the magnet is dropped prematurely

### ISSUE THREAD

**Issue by phet-steele** [phetsims/faradays-law#214]
1. Press Tab and Space to pick up the magnet with the keyboard
2. Press and hold 1 (or the others, but "1" will be used for this example)
3. While holding 1, either press Tab or Space to drop the magnet. Depending on which you choose, the little direction arrow may or may not go away, but the ghost image will always remain in place.
4. Release 1, the magnet will not move. (Somewhat expected?)
5. Return to the magnet, and pick it up with keyboard nav again.

No matter how often you press 2 or 3 at this point, the magnet will not move at all until you press 1 again, twice. This is the part that feels really buggy to me! If you want to have some more buggy fun, press the Flip Magnet button after step 4!

Seen on Win 10 Chrome. For phetsims/QA/issues/585.

<details>
<summary>Troubleshooting Information</summary>

URL: https://phet-dev.colorado.edu/html/faradays-law/1.4.0-rc.2/phet/faradays-law_all_phet.html
Version: 1.4.0-rc.2 2020-12-15 19:50:51 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Language: en-US
Window: 953x801
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
</details>

**Comment by jbphet** [comment]
This is an interesting case.  There was no handling in place for the situation where the magnet lost keyboard nav focus while auto-slide keys were pressed.  I've added it by created a `release` handler and making it behave as though any auto-slide keys that were down are considered up.

**Comment by KatieWoe** [comment]
Looks fixed in rc.4. Will reopen if something else shows up
