### ISSUE TITLE
Need new dev version that is both keyboard & mobile accessible for A11y Sims page

### ISSUE THREAD

**Issue by terracoda** [phetsims/faradays-law#219]
While testing https://phet-dev.colorado.edu/html/faradays-law/1.5.0-dev.1/phet/faradays-law_en_phet.html for #206, I noticed that I could no longer move the grabbed magnet with the keyboard and that the visual grab hint is askew on focus. The magnet is indeed grabbable and draggable on iOS, but not on MacOs with the keyboard.

I tested with 
- MacOS High Sierra 10.13.6 (which is not the latest MacOS)
- VoiceOver and Safari
- and Firefox and Chrome without a screen reader

Oh I just tested on Master, and I can move the magnet with the keyboard.

So the issue is with that dev version, not the sim.

I just need a new dev version to put on the A11y Sims page.

Not super high priority, but as soon as @jbphet or @jessegreenberg can give me one that would be nice. Assigning to @jbphet with low prioroty.

**Comment by jbphet** [comment]
Hmmm, I'm not sure what happened with 1.5.0-dev.1.  I may have picked up some transitional code or had some common repos on older revisions (I was doing some maintenance releases on other sims around the same time).  At any rate, I just did another dev version and testing keyboard interaction with the magnet, and it seems fine.

@terracoda - please try this one and see if it works better for you: https://phet-dev.colorado.edu/html/faradays-law/1.5.0-dev.2/phet/faradays-law_en_phet.html.

**Comment by terracoda** [comment]
Your awesome, thanks @jbphet.

**Comment by terracoda** [comment]
Accessible Sims page is updated with this prototype version of Faraday's Law that includes the interactive description icons.

Closing.
