### ISSUE TITLE
Feature request - a "field meter"

### ISSUE THREAD

**Issue by anirvon** [phetsims/faradays-law#220]
It would be very helpful to include a way to measure the magnetic field in the simulation using a "field meter", that shows the measured value of the magnetic field, like in the older Java-based simulation at https://phet.colorado.edu/sims/cheerpj/faraday/latest/faraday.html?simulation=magnet-and-compass. 
This would enable my students to perform calculations using this simulation.

If possible, other features like setting the strength of the magnet, changing the density of the field lines etc. would also be good to have. 

I am sorry for the spam if this is not the right place to request new features!

**Comment by jbphet** [comment]
@anirvon - Thanks for the request, and this is a fine place to put it.

@arouinfar - You're listed as one of the designers for this sim, and the only one who I think is available.  I believe the simulation that is linked in the user's request is actually from Faraday's Electromagnetic Lab, but I'm not certain, and I don't know what our plans are for porting that one.  Can you please log your input and we can decide how to address this request?

**Comment by arouinfar** [comment]
Thanks for reaching out @anirvon. @jbphet is correct, Magnet and Compass is a sub-set of the [Faraday's Electromagnetic Lab](https://phet.colorado.edu/en/simulation/legacy/faraday) simulation which hasn't yet been converted to HTML5. However, we do have a browser-compatible CheerpJ version available on the simulation page. The "Pickup Coil" tab of Faraday's Electromagnetic Lab is a more quantitative version of the Faraday's Law sim, and includes the requested features.
