### ISSUE TITLE
Model step skips some frames, and speeds up after switching out of sim's tab

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/faradays-law#29]
The model step for the coils and volt meter will only run on average every 30ms, while browsers usually run frames down to 16.7ms in-between (FaradaysLawModel's targetTickTime is 30ms). Is there a reason we can't run this every frame to improve the smoothness of the lightbulb animation?

Additionally, the code doesn't take into account large dt values in FaradaysLawModel's step(). What happens is that timeInterval becomes huge, and then the sims' model runs at twice the speed until timeInterval goes back down to ~0.

For example, if I launch the sim, switch to another browser tab and wait 1 minute, then after I switch back to the sim's tab it seems to run faster for ~30 seconds (no frames being skipped), and then slows back down afterwards.

Relevant code in FaradaysLawModel.js:
```js
step: function( dt ) {
  this.timeInterval += dt;
  if ( this.timeInterval > this.targetTickTime ) {
    this.timeInterval -= this.targetTickTime;
    this.coil1.step( this.modelTickTime );
    if ( this.showSecondCoil ) {
      this.coil2.step( this.modelTickTime );
    }
    this.voltMeterModel.step( this.modelTickTime );
  }
},
```

Code Review: https://github.com/phetsims/faradays-law/issues/26

**Comment by jbphet** [comment]
Fixed, closing.
