### ISSUE TITLE
Poor rendering of solenoid IE11 and FF 32.0.3

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/faradays-law#50]
![faradays](https://cloud.githubusercontent.com/assets/5631059/4548157/9b9e6f52-4e52-11e4-93b3-3f283e67c58f.PNG)

Troubleshooting information (do not edit):
Name: Faraday's Law
URL: http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.0.0-rc.1/faradays-law_en.html
Version: 1.0.0-rc.1
Features missing: touch, fullscreen
Flags: pointerEnabled, msPointerEnabled
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; Tablet PC 2.0; InfoPath.3; ASU2JS; rv:11.0) like Gecko
Language: en-US
Window: 1366x673
Pixel Ratio: 1/1
WebGL: WebGL 0.94
GLSL: WebGL GLSL ES 0.94
Vendor: Microsoft (Internet Explorer)
Vertex: attribs: 16 varying: 15 uniform: 512
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by jbphet** [comment]
This is still a problem as of the 1.0.2 release.  Since support for mipmaps has been added to Scenery since this issue was originally logged, I'm going to try using them instead of plain images to see if that resolves this issue.

**Comment by jbphet** [comment]
Changing the coils to be mipmaps improved things.  Here is before and after in Firefox 40.0.3 on Win7.

Before:
![fl-coils-old](https://cloud.githubusercontent.com/assets/3082831/10497419/059eb2f4-7283-11e5-8665-169edfcf20b1.png)

After:
![fl-coils-new](https://cloud.githubusercontent.com/assets/3082831/10497427/0e69923c-7283-11e5-9afe-c0a1c83a7341.png)

...and here is IE11 before:
![fl-coils-old-ie](https://cloud.githubusercontent.com/assets/3082831/10497598/f5de112e-7283-11e5-90d1-8b22fc92111b.png)

After:
![fl-coils-new-ie](https://cloud.githubusercontent.com/assets/3082831/10497605/0163a612-7284-11e5-912c-b22ca5b8eb6b.png)

**Comment by jbphet** [comment]
I think this has been adequately addressed.  Closing.

**Comment by ariel-phet** [comment]
:+1:
