### ISSUE TITLE
Add together API support

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-law#61]
Similar to https://github.com/phetsims/concentration/issues/34 we would like to instrument this simulation for API access.  We previously discussed adding support for concentration first, but I would like to investigate this as a second use case for ease of instrumentation.  I'll work in the `api` branch as I did for concentration, until the work can be reviewed by @jbphet.

**Comment by samreid** [comment]
Work completed above. Looks pretty good for arch.log=console as well as mirroring test.  Save/load from arbitrary state won't work perfectly, because not all of the transient model state is stored.  Ready for review and discussion with @jbphet.

**Comment by samreid** [comment]
@jbphet can we schedule a time to look at this together early this week?

**Comment by pixelzoom** [comment]
If possible, please rename the `api` branch to something more descriptive. See  phetsims/together#11.

**Comment by samreid** [comment]
It looks like we will abandon the `api` branch and continue work with the `together` branch, using the together.addComponent methodology.

**Comment by samreid** [comment]
API branch has been deleted.

**Comment by samreid** [comment]
After additional work in 0f84ad1d2c336323dcfa41abc7e92626311cda1b, d8aa83b23a8913b4af0b7b3cb96a7c22fa3662b0 and 388a9f13b5d89d53f43b13504c1b9a824ce6d8a6, my work is ready for discussion with @jbphet.

Summary of changes:
1. Added componentIDs to properties and user interface components
2. Added together.addComponent and arch.start/end calls to custom UI components
3. Added scripts to *_en.html
4. Added faradays-law-together-api.js

Let's discuss this soon--if this approach seems good then we should move into master when possible.

**Comment by samreid** [comment]
I reviewed this with @jbphet and he said it seems like a reasonable direction and he is ok to merge this to master.

**Comment by samreid** [comment]
Changes are merged in to master, closing.
