### ISSUE TITLE
Rename showCoilArrows

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-law#62]
While working on #61 I saw this code:

```js
    PropertySet.call( this, {
      showSecondCoil: false, // number of coils - 1 or 2
      showCoilArrows: true
    } );
```

it looks like `showCoilArrows` actually shows the arrows on the bar magnet before it is dragged.  Can/should this be renamed?

**Comment by jbphet** [comment]
Indeed, this was poorly named.  I've renamed it and will close.  Thanks for being observant.
