### ISSUE TITLE
branch: together

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-law#64]
Together instrumentation for faradays-law sim.

**Comment by jbphet** [comment]
The code from this branch was built and released to Metacog for a demo that they were doing at a trade show in June 2015.  There is a chance that a maintenance release will be needed at some point, but so far (as of late October 2015) there have been no such requests.  At some point, any subsequent releases of together-enabled code (now called phet-io) would come off of the master branch.  Once we've reached that point, this issue should be closed.

**Comment by jbphet** [comment]
I sent the following email to @kathy-phet and @ariel-phet:

K--- and A----,
 
I’m cleaning up some things as I go through the process of publishing some sims, and there is a branch for Faraday’s Law that contains the together-enabled code that we supplied to them for their demo in June.  I’d like to delete this branch and close the related issue if possible.  What would you estimate as the odds that we will do a maintenance release on this code, or on the versions of Color Vision, Concentration, or Molecules and Light that we supplied for this demo?
Thanks,
J---

**Comment by jbphet** [comment]
@ariel-phet responded:

Definitely a question for K----...I would be all in favor of deleting the branch. Together has changed quite a bit since then, so it seems like things would need a pretty reasonable update anyhow.

**Comment by zepumph** [comment]
@pixelzoom can this branch be deleted?

**Comment by pixelzoom** [comment]
No idea, not my branch. Ask @jbphet.

**Comment by jbphet** [comment]
I'm making an executive decision that this branch should be deleted.  The chances that we will ever need this are vanishingly small.

**Comment by zepumph** [comment]
Sounds good. It's deleted, thanks all.

**Comment by jbphet** [comment]
Reopening.  This branch was restored during an effort to recover some branches that were accidentally deleted.  This one had been _intentionally_ deleted, and now needs to be re-deleted.  See https://github.com/phetsims/special-ops/issues/198.

**Comment by jbphet** [comment]
Re-deletion complete.  Closing.
