### ISSUE TITLE
See-through magnet

### ISSUE THREAD

**Issue by phet-steele** [phetsims/faradays-law#68]
Does not block publication, but I've noticed on Win 8.1 IE 11 there is a slight opening in the magnet at the top that lets you look through it:

![voltage peek](https://cloud.githubusercontent.com/assets/5863899/10738001/d4b88dde-7bda-11e5-9332-959e8bbbbc18.PNG)

![coil peek](https://cloud.githubusercontent.com/assets/5863899/10738022/f2438048-7bda-11e5-9c28-3c80ff0e9a6a.PNG)

Name: ‪Faraday's Law‬
URL: http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.1.0-rc.1/faradays-law_en.html
Version: 1.1.0-rc.1 2015-10-21 22:21:53 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36
Language: en-US
Window: 1366x643
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"11bc6a6d","branch":"HEAD"},"axon":{"sha":"e2237347","branch":"HEAD"},"babel":{"sha":"40d73ff6","branch":"master"},"brand":{"sha":"8a756e53","branch":"HEAD"},"chipper":{"sha":"157b9cf3","branch":"HEAD"},"dot":{"sha":"d99cbe46","branch":"HEAD"},"faradays-law":{"sha":"08f7de35","branch":"1.1"},"joist":{"sha":"121bb0de","branch":"HEAD"},"kite":{"sha":"40dc703a","branch":"HEAD"},"phet-core":{"sha":"e9f36af1","branch":"HEAD"},"phetcommon":{"sha":"0e4754fe","branch":"HEAD"},"scenery":{"sha":"2edf8a01","branch":"HEAD"},"scenery-phet":{"sha":"88ade507","branch":"HEAD"},"sherpa":{"sha":"1759eade","branch":"HEAD"},"sun":{"sha":"b66398a5","branch":"HEAD"},"tandem":{"sha":"c54f1082","branch":"HEAD"},"vibe":{"sha":"4b94a32b","branch":"HEAD"}}

**Comment by ariel-phet** [comment]
@jbphet - this seems like a low priority, but a nice detail to fix at some point.

**Comment by jbphet** [comment]
Good catch on this.  There was a bug with the way that the top and side were being drawn.  It was a fairly simple fix, so I've taken care of it on master and on the 1.1 branch.  Closing.
