### ISSUE TITLE
Rectangular artifacts in chrome

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-law#75]
Here's a new one, as I bump the magnet against the left side of the screen, the leftmost rectangle changes shades of blue:

![image](https://cloud.githubusercontent.com/assets/679486/18774525/51646316-8117-11e6-9dc1-5d725c68c64f.png)

![image](https://cloud.githubusercontent.com/assets/679486/18774529/58933d9c-8117-11e6-923e-3746f487246a.png)

Present in this version in chrome, not seen in firefox:

Report a Problem

Please copy and paste the information below into an email to phethelp@colorado.edu, and then fill in the blanks. 

Test device:

Operating System:

Browser:

Problem description:

Steps to reproduce:

Severity:

Screenshots:

Troubleshooting information (do not edit):
Name: ‪Faraday's Law‬
URL: https://phet.colorado.edu/sims/html/faradays-law/latest/faradays-law_en.html
Version: 1.1.6 2016-09-18 14:53:14 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36
Language: en-US
Window: 1366x592
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"11bc6a6d","branch":"HEAD"},"axon":{"sha":"202abb27","branch":"HEAD"},"babel":{"sha":"7fb58abd","branch":"master"},"brand":{"sha":"06cec00d","branch":"HEAD"},"chipper":{"sha":"d13a1dda","branch":"HEAD"},"dot":{"sha":"b9e3c1e0","branch":"HEAD"},"faradays-law":{"sha":"f9015be7","branch":"HEAD"},"joist":{"sha":"f250082c","branch":"HEAD"},"kite":{"sha":"7f2df7e9","branch":"HEAD"},"phet-core":{"sha":"12bc1541","branch":"HEAD"},"phetcommon":{"sha":"71d66069","branch":"HEAD"},"scenery":{"sha":"e2949e56","branch":"HEAD"},"scenery-phet":{"sha":"0539f7b5","branch":"HEAD"},"sherpa":{"sha":"f3cf6285","branch":"HEAD"},"sun":{"sha":"f678dd20","branch":"HEAD"},"tandem":{"sha":"210ece84","branch":"HEAD"},"vibe":{"sha":"e49a0e58","branch":"HEAD"}}

Tagging @jbphet since it is Faraday's Law.
Tagging @jonathanolson since it may impact the way things are done in scenery.
Tagging @ariel-phet in case he wants to prioritize/triage/assign/etc.  Are other manifestations of this bug likely to surface elsewhere? I don't know.

**Comment by jonathanolson** [comment]
Interesting. Unable so far to reproduce on windows.

**Comment by samreid** [comment]
Problem not observed in Version 62.0.3202.94 (Official Build) (64-bit), closing.
