### ISSUE TITLE
Keyboard Navigation Dialog

### ISSUE THREAD

**Issue by arouinfar** [phetsims/faradays-law#82]
I've reviewed the latest dev ([1.4.0-dev.4](http://www.colorado.edu/physics/phet/dev/html/faradays-law/1.4.0-dev.4/faradays-law_en.html?accessibility)) and here's a rough draft of the dialog content. 

**Move Magnet** 
Move magnet: [arrow keys] or [WASD]
Move faster: [Shift] + [arrow keys] or [Shift] + [WASD]

**General Navigation**
Move to next item: [Tab]
Move to previous item: [Shift] + [Tab]
Exit this dialog: [Esc]

The "Move Magnet" section will be formatted like the "Move Book" section in Friction. We're still deciding on the stacked vs. super compact layout in https://github.com/phetsims/friction/issues/45.

 @terracoda can you review? Should we also include information about the checkbox (space), radio group (arrow keys), or button (space or enter)? It seems a bit incomplete to leave them out, but I've omitted them because we did not include similar shortcuts in previous iterations of the BASE dialog.

**Comment by terracoda** [comment]
@arouinfar, thus far, in my experience, users have known how to use native controls like simple buttons, radio buttons, and checkboxes. For this sim, I think is safe to leave them off for now, and focus on the custom interaction, moving the magnet.

**Comment by terracoda** [comment]
**Move Magnet**
Move magnet: [arrow keys] or [WASD]
Move faster: [Shift] + [arrow keys] or [Shift] + [WASD]

**General Navigation**
Move to next item: [Tab]
Move to previous item: [Shift] + [Tab]
Exit this dialog: [Esc]

**Comment by terracoda** [comment]
@arouinfar, assigning back to you. Hope that's ok.

**Comment by arouinfar** [comment]
> @arouinfar, thus far, in my experience, users have known how to use native controls like simple buttons, radio buttons, and checkboxes. 

Good to know @terracoda! Thanks.

Here's a mockup of the dialog @terracoda. Can you take a look?
![screen shot 2017-10-09 at 1 43 04 pm](https://user-images.githubusercontent.com/8419308/31355512-d0e34dac-acf7-11e7-8120-79efda0f846c.png)

**Comment by terracoda** [comment]
@arouinfar, looks good, except one tiny change. I think we had agreed earlier to change, "Exit this dialog:" to "Exit a dialog:". 

Is the "this" intentional?

**Comment by terracoda** [comment]
@arouinfar, yes, we agreed on the wording change when discussing the dialogs for Friction https://github.com/phetsims/friction/issues/45 Molecules and Light https://github.com/phetsims/molecules-and-light/issues/160.

**Comment by arouinfar** [comment]
Thanks @terracoda! It's possible I mocked up the dialog before we settled on "Exit a dialog", so the wording was not intentional. The scene selection radio buttons act as a group, so should we use the group version of the General Navigation section?

![image](https://user-images.githubusercontent.com/8419308/32012237-754f6dca-b974-11e7-9e07-3a2f877b4dd1.png)

**Comment by terracoda** [comment]
@arouinfar, looks good. Yes, since the scene selections here are two radios (a group), but to use the group version. In BASE, we are experimenting with a checkbox for the Two-balloon Experiments because it is less verbose from a screen reader's perspective. We will see what we learn from that.

**Comment by arouinfar** [comment]
Great! Thanks @terracoda. 

Off to @jessegreenberg for implementation/reassingment!
![image](https://user-images.githubusercontent.com/8419308/32013587-cc82d574-b978-11e7-9acc-0c3eb17d4564.png)

**Comment by terracoda** [comment]
Oops, I marked hooray on the old version and the latest version. The latest version is good.

**Comment by terracoda** [comment]
Over to you @jessegreenberg .

**Comment by arouinfar** [comment]
No worries @terracoda. The dialogs were identical, except for the alignment of the dialog title (I forgot to re-center it after making the dialog wider).

**Comment by zepumph** [comment]
I'm doing a lot of work for this repo right now, so I'll take this one on. I'm not sure the status of this now that the IDRC is designing a new mode of keyboard nav on it. On hold for now as we work on #89.

**Comment by zepumph** [comment]
I don't think we should implement this right now, since the keyboard interface for the magnet now totally different (after prototyping for the IDRC). Unassigning until the a11y features of this sim stabilize.

**Comment by emily-phet** [comment]
Issue resolved in #176
