### ISSUE TITLE
Can we delete phet-io-api.json?

### ISSUE THREAD

**Issue by zepumph** [phetsims/faradays-law#88]
@samreid I can't find the issue where we were prototyping this, but I think that the plan is to use latest versions from the phet-io website instead. Can this be deleted?

**Comment by samreid** [comment]
The latest notes in https://github.com/phetsims/phet-io/issues/1221#issuecomment-331579394 indicate we wanted to commit the latest stable API to master.  Has there been subsequent discussion or insight about this?

**Comment by zepumph** [comment]
I thought that we were going with a diffing tool that runs on bayes and compares master to latest phet-io version, as discussed in https://github.com/phetsims/phet-io-wrappers/issues/30 (updated 20 days ago)

**Comment by samreid** [comment]
Thanks for jogging my memory, that sounds good, thanks!  I'll delete phet-io-api.json.

**Comment by samreid** [comment]
Deleted, closing.
