### ISSUE TITLE
Prototype for magnet keyboard interaction

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/faradays-law#89]
We would like to create a prototype from the IDRC designs for interacting with the magnet with a keyboard. The interaction should work such that:
- When an arrow key is pressed, the magnet should continuously move in the direction of the arrow.
- If the same arrow is pressed again, the magnet will move faster in that direction. Repeat until a max speed (maybe after 3-5 presses)
- If any other key is pressed after magnet moves in a direction, it should stop moving.

@zepumph agreed to look into this, thanks!

**Comment by zepumph** [comment]
I'm not sure how to start on this. I don't think I want to modify KeyboardDragHandler, so instead I want a new handler. It can step the position as needed based on the state of the arrow keys, which dictate the velocity. I'll see if I can get the step function to work as I need it to.

**Comment by zepumph** [comment]
Have a look at this one. It is pretty basic, but I think it sets us up for design really nicely. @emily-phet @jessegreenberg @terracoda, you can play with it here, https://www.colorado.edu/physics/phet/dev/html/faradays-law/1.4.0-dev.5/faradays-law_en.html?accessibility

**Comment by zepumph** [comment]
@emily-phet can you please send this to the IDRC if you think it is good enough for their designing needs.

**Comment by terracoda** [comment]
@zepumph, this is really cool. Nice work.

Personally, I think the differences between speed could be greater. The first speed being very slow, and then the second speed being what the first speed is now, and then a fast speed.

Also, hitting the space key does swap directions. Are you going to try that, or is that for later?

Again, nice work.

**Comment by zepumph** [comment]
Here is the next version, with updated speeds and space bar for reversing directions.  https://www.colorado.edu/physics/phet/dev/html/faradays-law/1.4.0-dev.7/faradays-law_en.html?accessibility

**Comment by zepumph** [comment]
I emailed the next version to @emily-phet to pass on to the IDRC, from here we will wait for feedback. On hold until then.

**Comment by emily-phet** [comment]
Behavior of magnet control with keyboard designed, discussed, and implemented through other issues.
