### ISSUE TITLE
Do we need small coil images?

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-law#91]
From review in https://github.com/phetsims/faradays-law/issues/86

There are 4 images dedicated to being "small", but I wonder if that is really necessary given that we are using mipmap plugin and firefox has had rendering improvements lately.

**Comment by samreid** [comment]
Today I wrote to @ariel-phet that we may need to test across multiple platform in order to simplify the rendering of the smaller coil images.

**Comment by samreid** [comment]
The original images look great on Mac Firefox 57 with mipmapping:
![image](https://user-images.githubusercontent.com/679486/33087054-b8fd6b52-cea6-11e7-91e4-bc3093c33a80.png)

I'll commit/push and we can test more broadly in the next dev test.

**Comment by samreid** [comment]
Pushed and ready for testing in next dev version.

**Comment by samreid** [comment]
@phet-steele can you test this issue in https://www.colorado.edu/physics/phet/dev/html/faradays-law/1.4.0-dev.6/faradays-law_en.html particularly on some firefoxes?

**Comment by phet-steele** [comment]
Images look great on FF 57 and iPad 2.
