### ISSUE TITLE
Dev Testing for performance

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-law#95]
From https://github.com/phetsims/faradays-law/issues/86

- [x] Does the sim perform as desired across the range of supported platforms? (eg, not too slow on slow platforms, not too fast on fast platforms)
- [x] Are UI components sufficiently responsive? (especially continuous UI components, such as sliders)

https://www.colorado.edu/physics/phet/dev/html/faradays-law/1.4.0-dev.6/faradays-law_en.html can be used for testing.

May not require much testing--it's not too demanding of a sim that's already published, would just be good to double check on our slowest platforms.

**Comment by phet-steele** [comment]
Dragging the magnet lags a bit behind your cursor on Edge, but other than that performance checks out.
