### ISSUE TITLE
delete babel/autoport/faraday/

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/faradays-law#97]
After publishing the first HTML5 version of a sim ported from Java/Flash, the string files in babel/autoport/{{REPO}} are supposed to be manually deleted. That hasn't been done for this sim.

**Comment by jbphet** [comment]
I just took a look, and I don't think the strings in the `/autoport/faraday/' directory are for Faraday's Law, they are from Faraday's Electromagnetic Lab. @pixelzoom - can you take a look and see if you concur?

**Comment by pixelzoom** [comment]
Ah, right you are, I forgot that we had multiple "faraday" sims.  Sorry to bother you. Closing.
