### ISSUE TITLE
PhET-iO Data Stream Design

### ISSUE THREAD

**Issue by samreid** [phetsims/faradays-law#98]
As part of #79 and more generally https://github.com/phetsims/phet-io/issues/1234 we would like to review the data stream to make sure it is as desired before we publish the stable version.  I'll paste my notes from today's meeting.  We also decided that @zepumph and I can take a look and try to extrapolate from today's decisions, but that we should also have at least one other meeting about it.

- [ ] get rid of screen activation message

```js
 "children": [
    {
      "messageIndex": 1,
      "eventType": "model",
      "phetioID": "faradaysLaw.faradaysLawScreen.activeProperty",
      "componentType": "PropertyIO.<BooleanIO>",
      "event": "changed",
      "time": 1512682232506,
      "parameters": {
        "oldValue": false,
        "newValue": true
      }
    }
  ]
}
```

- [ ] Should the screen index property start at 0 or 1?  See if it matches query parameter.  If not, should it?

KP: It is helpful to separate view/model in the tandems

AP: The "controlPanel" part of the tandem may be useful.  Seems like we should discuss with JB and JG to see if they would leverage it.

- [x] We are leaning toward eliminating "controlPanel" but will check with JB and JG first.

KP: Should there be an option for? Maybe we can add an option that would include mouse + touch presses (and location).  Seems good to just use mirror inputs for this.

Diana making heat maps

- [ ] KP: high frequency messages may be too performance demanding, and may require a pre-filter.

AP: I noticed there is a controller message that goes to the model, but doesn't reflect in a corresponding view message.  For instance: if you show the 2nd coil in faraday's law, there is a message from faradaysLaw.faradaysLawScreen.view.controlPanel.radioButtonGroup.doubleCoilRadioButton that cascades to faradaysLaw.faradaysLawScreen.model.showTopCoilProperty but it never shows up in something like faradaysLaw.faradaysLawScreen.view.topCoilVisible.
	SR: Perhaps a view message would be redundant?

For the radio buttons, we should discuss with Taliesin whether it should be treated as togglebutton/checkbox/radio buttons for accessibility.  We can use that as guidance for how to PhET-iO instrument it.
	AP thinks it will be a toggle or checkbox, not radio buttons.

- [x] change flippedProperty to PropertyIO.<StringIO>
magnetOrientation: 'NS' | 'SN'.
KP: check on this during accessibility review. Will it work for descriptive texts?

**Comment by samreid** [comment]
Notes are in the Keyboard Navigation Meeting google doc.  There is time pressure to get BASE published quickly, so we may proceed as-is, which is "scenery radio buttons with checkbox a11y peer".  In the future, we may change this to separate screens, a radio button peer or an actual checkbox.

**Comment by samreid** [comment]
@jessegreenberg, @emily-phet was wondering what you thought about this part:

> change flippedProperty to PropertyIO.
magnetOrientation: 'NS' | 'SN'.
KP: check on this during accessibility review. Will it work for descriptive texts?

This means we are considering changing the “flipped” from a boolean true/false property to a categorical property and not sure how it will impact the a11y side.

**Comment by samreid** [comment]
> get rid of screen activation message

This will be tricky since the sim main declares the Screen instances, and they all default to active:false.  Our best bet would be to remove this from the data stream, but then we won't see any messages when screens change.  @zepumph what do you think of `phetioEvents:false` for this?  I don't know if sonification wrappers are listening to this in the data stream or wiring up listeners to it (hopefully the latter).

**Comment by samreid** [comment]
> Should the screen index property start at 0 or 1? See if it matches query parameter. If not, should it?

I'm not seeing any screen index in the data stream for a single screen sim. Am I missing it?  Or is it more about supporting multiscreen sims for the future?

**Comment by samreid** [comment]
> We are leaning toward eliminating "controlPanel" but will check with JB and JG first.

@jbphet and @jessegreenberg do you know if phet-io wrappers for this sim are relying on the "controlPanel" part of the tandems?  We are thinking of truncating e.g., `faradaysLaw.faradaysLawScreen.view.controlPanel.coilRadioButtonGroup.doubleCoilRadioButton` to `faradaysLaw.faradaysLawScreen.view.coilRadioButtonGroup.doubleCoilRadioButton`

**Comment by jessegreenberg** [comment]
> This means we are considering changing the “flipped” from a boolean true/false property to a categorical property

I can't think of a way this would impact a11y, this implementation detail shouldn't change how the magnet is described.

> @jbphet and @jessegreenberg do you know if phet-io wrappers for this sim are relying on the "controlPanel" part of the tandems?

Sorry, I have no experience with phet-io wrappers for this sim.

**Comment by jbphet** [comment]
There are no sonification wrappers for Faraday's Law yet, so it shouldn't be a problem.  There will probably be some work on such a wrapper starting in about two weeks.

**Comment by samreid** [comment]
> get rid of screen activation message

I'm inclined to leave this message enabled as a "feature" because it seems too brittle or complex to try to get the value right on initialization or have the framework create that property.

**Comment by samreid** [comment]
High frequency messages being discussed in https://github.com/phetsims/phet-io/issues/1227

**Comment by samreid** [comment]
I addressed, discussed or commented on all issues in the description, the remaining work is in https://github.com/phetsims/phet-io/issues/1227 and https://github.com/phetsims/faradays-law/issues/100, closing.
